### ISSUE TITLE
Unable to start Dallinger after updating—possible version compatibility issue?

### ISSUE THREAD

**Issue by a-paxton** [Dallinger/Dallinger#1013]
After updating Dallinger from v3.4.1 to `master` using the [Anaconda installation instructions](http://dallinger.readthedocs.io/en/v3.4.1/dallinger_with_anaconda.html), I am unable to start Dallinger.

## Expected Behavior
Dallinger should be updated and and start appropriately.

## Current Behavior
See traceback:
```(dallinger341) $ dallinger --version
Traceback (most recent call last):
  File "/anaconda3/envs/dallinger341/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/anaconda3/envs/dallinger341/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/envs/dallinger341/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/anaconda3/envs/dallinger341/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/anaconda3/envs/dallinger341/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Dallinger/dallinger/__init__.py", line 3, in <module>
    from . import (
  File "/Dallinger/dallinger/command_line.py", line 38, in <module>
    from dallinger import data
  File "/Dallinger/dallinger/data.py", line 33, in <module>
    import odo
  File "/anaconda3/envs/dallinger341/lib/python2.7/site-packages/odo/__init__.py", line 65, in <module>
    from .backends.dask import dask
  File "/anaconda3/envs/dallinger341/lib/python2.7/site-packages/odo/backends/dask.py", line 13, in <module>
    import dask.dataframe as dd
  File "/anaconda3/envs/dallinger341/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/anaconda3/envs/dallinger341/lib/python2.7/site-packages/dask/dataframe/core.py", line 40, in <module>
    pd.core.computation.expressions.set_use_numexpr(False)
AttributeError: 'module' object has no attribute 'expressions'
```

## Context
Trying to update to `master` version of Dallinger

## Your Environment
* *Dallinger version used*: updating from 3.4.1 to current `master` with Anaconda
* *Operating System and version (desktop or mobile)*: desktop, Mac OS X 10.13.4

**Comment by a-paxton** [comment]
After running `conda update dask` (updated to version `0.17.5`), I am now able to run Dallinger as expected:

```
(dallinger341) $ pip show dask
Name: dask
Version: 0.17.5
Summary: Parallel PyData with Task Scheduling
Home-page: http://github.com/dask/dask/
Author: None
Author-email: None
License: BSD
Location: /anaconda3/envs/dallinger341/lib/python2.7/site-packages
Requires: 
Required-by: distributed, blaze
(dallinger341) $ dallinger --version
4.0.0
```
