### ISSUE TITLE
Document the “the egg thingy”

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1238]
This is likely a developer only issue and encountered when running a dallinger branch in sandbox mode. 

## Expected Behavior
Expected my experiment running in sandbox mode to work

## Current Behavior
I ran the bartlett experiment using python2 in a freshly installed python2 virtualenv
When running in sandbox mode I got this issue
```
❯❯ Pushing code to Heroku...
Traceback (most recent call last):
  File "/home/witek/.virtualenvs/D2Dallinger/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/home/witek/.virtualenvs/D2Dallinger/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/witek/.virtualenvs/D2Dallinger/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/witek/.virtualenvs/D2Dallinger/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/witek/.virtualenvs/D2Dallinger/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/witek/.virtualenvs/D2Dallinger/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/witek/dev/jazkarta/D2Dallinger/Dallinger/dallinger/command_line.py", line 110, in wrapper
    result = func(*args, **kwargs)
  File "/home/witek/dev/jazkarta/D2Dallinger/Dallinger/dallinger/command_line.py", line 318, in sandbox
    _deploy_in_mode('sandbox', app=app, verbose=verbose, log=log)
  File "/home/witek/dev/jazkarta/D2Dallinger/Dallinger/dallinger/deployment.py", line 353, in _deploy_in_mode
    deploy_sandbox_shared_setup(log, verbose=verbose, app=app)
  File "/home/witek/dev/jazkarta/D2Dallinger/Dallinger/dallinger/deployment.py", line 309, in deploy_sandbox_shared_setup
    git.push(remote="heroku", branch="HEAD:master")
  File "/home/witek/dev/jazkarta/D2Dallinger/Dallinger/dallinger/utils.py", line 105, in push
    self._run(cmd)
  File "/home/witek/dev/jazkarta/D2Dallinger/Dallinger/dallinger/utils.py", line 118, in _run
    raise GitError(str(e))
dallinger.utils.GitError: Command: "git push heroku HEAD:master": Error: "remote: Compressing source files... done.        remote: Building source:        remote: remote: -----> Python app detected        remote:  !     The latest version of Python 3.6 is python-3.6.6 (you are using python-3.6.4, which is unsupported).        remote:  !     We recommend upgrading by specifying the latest version (python-3.6.6).        remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes        remote: -----> Installing python-3.6.4        remote: -----> Installing pip        remote: -----> Installing SQLite3        remote: -----> Installing requirements with pip        remote:        Collecting dallinger==4.0.0 (from -r /tmp/build_df9b62be90bf0bc0553eac9debd9a404/requirements.txt (line 1))        remote:          Could not find a version that satisfies the requirement dallinger==4.0.0 (from -r /tmp/build_df9b62be90bf0bc0553eac9debd9a404/requirements.txt (line 1)) (from versions: 2.0.1, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.3.0, 3.4.0, 3.4.1)        remote:        No matching distribution found for dallinger==4.0.0 (from -r /tmp/build_df9b62be90bf0bc0553eac9debd9a404/requirements.txt (line 1))        remote:  !     Push rejected, failed to compile Python app.        remote: remote:  !     Push failed        remote: Verifying deploy...        remote: remote: !    Push rejected to dlgr-01629166.        remote: To https://git.heroku.com/dlgr-01629166.git ! [remote rejected] HEAD -> master (pre-receive hook declined)error: failed to push some refs to 'https://git.heroku.com/dlgr-01629166.git'"
(D2Dallinger) witek@ubuntu:~/dev/jazkarta/D2Dallinger/Dallinger/demos/dlgr/demos/bartlett1932$
```

To fix this I needed to specify my dallinger branch in the requirements.txt file of my experiment (bartlett)
```
-e git://github.com/Dallinger/Dallinger.git@stories/375-pinning-jms#egg=dallinger[data]
dallinger==4.0.0
```

This is not documented anywhere.
I propose to include it in the troubleshooting section, and potentially link to the **Troubleshooting** section from the **Demoing Dallinger** section where the user/developer ends up after installing Dallinger. Although perhaps that is not necessary as if one is doing this sort of thing, one is likely a developer and should be expected to find the Troubleshooting section independently.

## Your Environment
Ubuntu 16.04

**Comment by witekdev** [comment]
To my knowledge the only location where we mention anything about ``` -e ``` is in the install dallinger for developers and we simply state: 
```pip install -e .[data] ```

This is something that has snagged me and several other people working on their own experiments.

**Comment by jessesnyder** [comment]
There are two separate questions here, right? One is whether we should document how to use a git checkout of a specific branch of dallinger when deploying to heroku. The second is whether that checkout needs to be installed in "editable" (`-e`) mode on the remote server. The first seems uncontroversial. On the second, I don't remember if there was a specific reason to use `-e`; was it a requirement for including the `[data]` extra?
