### ISSUE TITLE
Read the docs - building latest dallinger documentation failed

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1284]
The latest docs merged to master did not show up here:
http://docs.dallinger.io/en/latest/
https://readthedocs.org/projects/dallinger/

Look into why this is failing.

**Comment by witekdev** [comment]
This is the last successful build of latest, 5 weeks ago (13 July 2018)
https://readthedocs.org/projects/dallinger/builds/7480139/

**Comment by witekdev** [comment]
@alecpm Looks like that was due to some changes you made:
https://github.com/Dallinger/Dallinger/commit/090763a498acd4cd32e9cac04b8df6c97922a829
Failed build log here:
```
Running Sphinx v1.7.6
  adding: bartlett1932/ (stored 0%)
  adding: bartlett1932/templates/ (stored 0%)
  adding: bartlett1932/templates/consent.html (deflated 48%)
  adding: bartlett1932/templates/layout.html (deflated 55%)
  adding: bartlett1932/templates/exp.html (deflated 54%)
  adding: bartlett1932/templates/ad.html (stored 0%)
  adding: bartlett1932/templates/instructions.html (deflated 54%)
  adding: bartlett1932/models.py (deflated 51%)
  adding: bartlett1932/demo.ipynb (deflated 66%)
  adding: bartlett1932/experiment.py (deflated 66%)
  adding: bartlett1932/config.txt (deflated 37%)
  adding: bartlett1932/static/ (stored 0%)
  adding: bartlett1932/static/scripts/ (stored 0%)
  adding: bartlett1932/static/scripts/experiment.js (deflated 68%)
  adding: bartlett1932/static/scripts/store+json2.min.js (deflated 60%)
  adding: bartlett1932/static/scripts/markdown.min.js (deflated 64%)
  adding: bartlett1932/static/favicon.ico (deflated 63%)
  adding: bartlett1932/static/stimuli/ (stored 0%)
  adding: bartlett1932/static/stimuli/raid.md (deflated 53%)
  adding: bartlett1932/static/stimuli/tennis.md (deflated 47%)
  adding: bartlett1932/static/stimuli/outwit.md (deflated 50%)
  adding: bartlett1932/static/stimuli/cricket.md (deflated 50%)
  adding: bartlett1932/static/stimuli/species.md (deflated 48%)
  adding: bartlett1932/static/stimuli/ghosts.md (deflated 53%)
  adding: bartlett1932/static/stimuli/moochi.md (deflated 50%)
  adding: bartlett1932/static/stimuli/vagabond.md (deflated 45%)
  adding: bartlett1932/static/images/ (stored 0%)
  adding: bartlett1932/static/images/logo.png (stored 0%)
  adding: bartlett1932/static/css/ (stored 0%)
  adding: bartlett1932/static/css/bootstrap.min.css (deflated 83%)
  adding: bartlett1932/README.md (deflated 44%)
  adding: bartlett1932/requirements.txt (stored 0%)
  adding: bartlett1932/__init__.py (stored 0%)
  adding: mcmcp/ (stored 0%)
  adding: mcmcp/templates/ (stored 0%)
  adding: mcmcp/templates/consent.html (stored 0%)
  adding: mcmcp/templates/instructions/ (stored 0%)
  adding: mcmcp/templates/instructions/instruct-ready.html (deflated 54%)
  adding: mcmcp/templates/layout.html (stored 0%)
  adding: mcmcp/templates/exp.html (deflated 62%)
  adding: mcmcp/templates/ad.html (stored 0%)
  adding: mcmcp/models.py (deflated 66%)
  adding: mcmcp/experiment.py (deflated 63%)
  adding: mcmcp/config.txt (deflated 37%)
  adding: mcmcp/static/ (stored 0%)
  adding: mcmcp/static/scripts/ (stored 0%)
  adding: mcmcp/static/scripts/raphael-min.js (deflated 65%)
  adding: mcmcp/static/scripts/experiment.js (deflated 73%)
  adding: mcmcp/static/scripts/markdown.min.js (deflated 64%)
  adding: mcmcp/static/favicon.ico (deflated 63%)
  adding: mcmcp/static/images/ (stored 0%)
  adding: mcmcp/static/images/logo.png (stored 0%)
  adding: mcmcp/static/css/ (stored 0%)
  adding: mcmcp/static/css/bootstrap.min.css (deflated 83%)
  adding: mcmcp/static/css/custom.css (deflated 34%)
  adding: mcmcp/README.md (deflated 43%)
  adding: mcmcp/requirements.txt (stored 0%)
  adding: mcmcp/__init__.py (stored 0%)
  adding: rogers/ (stored 0%)
  adding: rogers/tests/ (stored 0%)
  adding: rogers/tests/tests.py (deflated 80%)
  adding: rogers/templates/ (stored 0%)
  adding: rogers/templates/consent.html (deflated 36%)
  adding: rogers/templates/instructions/ (stored 0%)
  adding: rogers/templates/instructions/instruct-2.html (deflated 63%)
  adding: rogers/templates/instructions/instruct-1.html (deflated 54%)
  adding: rogers/templates/instructions/instruct-ready.html (deflated 51%)
  adding: rogers/templates/layout.html (stored 0%)
  adding: rogers/templates/stage.html (deflated 62%)
  adding: rogers/templates/ad.html (stored 0%)
  adding: rogers/models.py (deflated 72%)
  adding: rogers/experiment.py (deflated 74%)
  adding: rogers/config.txt (deflated 36%)
  adding: rogers/static/ (stored 0%)
  adding: rogers/static/scripts/ (stored 0%)
  adding: rogers/static/scripts/raphael-min.js (deflated 65%)
  adding: rogers/static/scripts/experiment.js (deflated 68%)
  adding: rogers/static/favicon.ico (deflated 63%)
  adding: rogers/static/images/ (stored 0%)
  adding: rogers/static/images/demo_social.jpg (deflated 6%)
  adding: rogers/static/images/blue_social.jpg (deflated 6%)
  adding: rogers/static/images/logo.png (stored 0%)
  adding: rogers/static/images/demo.jpg (deflated 7%)
  adding: rogers/static/images/grey.jpg (deflated 10%)
  adding: rogers/static/images/yellow_social.jpg (deflated 5%)
  adding: rogers/static/images/yellow.jpg (deflated 7%)
  adding: rogers/static/images/blue.jpg (deflated 48%)
  adding: rogers/static/css/ (stored 0%)
  adding: rogers/static/css/bootstrap.min.css (deflated 83%)
  adding: rogers/README.md (deflated 32%)
  adding: rogers/requirements.txt (stored 0%)
  adding: rogers/__init__.py (stored 0%)
  adding: rogers/.gitignore (deflated 2%)
  adding: twentyfortyeight/ (stored 0%)
  adding: twentyfortyeight/LICENSE.txt (deflated 41%)
  adding: twentyfortyeight/templates/ (stored 0%)
  adding: twentyfortyeight/templates/consent.html (stored 0%)
  adding: twentyfortyeight/templates/instructions/ (stored 0%)
  adding: twentyfortyeight/templates/instructions/instruct-ready.html (deflated 53%)
  adding: twentyfortyeight/templates/layout.html (deflated 9%)
  adding: twentyfortyeight/templates/exp.html (deflated 75%)
  adding: twentyfortyeight/templates/ad.html (stored 0%)
  adding: twentyfortyeight/experiment.py (deflated 53%)
  adding: twentyfortyeight/config.txt (deflated 37%)
  adding: twentyfortyeight/static/ (stored 0%)
  adding: twentyfortyeight/static/scripts/ (stored 0%)
  adding: twentyfortyeight/static/scripts/classlist_polyfill.js (deflated 64%)
  adding: twentyfortyeight/static/scripts/game_manager.js (deflated 70%)
  adding: twentyfortyeight/static/scripts/html_actuator.js (deflated 69%)
  adding: twentyfortyeight/static/scripts/animframe_polyfill.js (deflated 64%)
  adding: twentyfortyeight/static/scripts/experiment.js (deflated 37%)
  adding: twentyfortyeight/static/scripts/tile.js (deflated 61%)
  adding: twentyfortyeight/static/scripts/grid.js (deflated 72%)
  adding: twentyfortyeight/static/scripts/keyboard_input_manager.js (deflated 70%)
  adding: twentyfortyeight/static/scripts/local_storage_manager.js (deflated 68%)
  adding: twentyfortyeight/static/scripts/bind_polyfill.js (deflated 37%)
  adding: twentyfortyeight/static/scripts/application.js (deflated 26%)
  adding: twentyfortyeight/static/favicon.ico (deflated 90%)
  adding: twentyfortyeight/static/images/ (stored 0%)
  adding: twentyfortyeight/static/images/logo.png (stored 0%)
  adding: twentyfortyeight/static/images/screenshot.png (deflated 11%)
  adding: twentyfortyeight/static/css/ (stored 0%)
  adding: twentyfortyeight/static/css/main.css (deflated 86%)
  adding: twentyfortyeight/static/css/fonts/ (stored 0%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Light-webfont.woff (deflated 0%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Bold-webfont.eot (deflated 0%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Light-webfont.eot (deflated 0%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Bold-webfont.svg (deflated 79%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Regular-webfont.woff (deflated 0%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Bold-webfont.woff (deflated 0%)
  adding: twentyfortyeight/static/css/fonts/clear-sans.css (deflated 78%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Regular-webfont.eot (deflated 0%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Regular-webfont.svg (deflated 79%)
  adding: twentyfortyeight/static/css/fonts/ClearSans-Light-webfont.svg (deflated 77%)
  adding: twentyfortyeight/static/css/helpers.scss (deflated 67%)
  adding: twentyfortyeight/static/css/main.scss (deflated 72%)
  adding: twentyfortyeight/static/css/bootstrap.min.css (deflated 83%)
  adding: twentyfortyeight/README.md (deflated 26%)
  adding: twentyfortyeight/requirements.txt (stored 0%)
  adding: twentyfortyeight/__init__.py (stored 0%)
  adding: twentyfortyeight/.jshintrc (deflated 59%)
  adding: twentyfortyeight/screenshot.png (deflated 11%)
  adding: function_learning/ (stored 0%)
  adding: function_learning/templates/ (stored 0%)
  adding: function_learning/templates/consent.html (deflated 57%)
  adding: function_learning/templates/instructions/ (stored 0%)
  adding: function_learning/templates/instructions/instruct-2.html (deflated 62%)
  adding: function_learning/templates/instructions/instruct-1.html (deflated 47%)
  adding: function_learning/templates/instructions/instruct-3.html (deflated 51%)
  adding: function_learning/templates/instructions/instruct-ready.html (deflated 60%)
  adding: function_learning/templates/debriefing.html (deflated 52%)
  adding: function_learning/templates/layout.html (stored 0%)
  adding: function_learning/templates/exp.html (deflated 62%)
  adding: function_learning/templates/default.html (deflated 40%)
  adding: function_learning/templates/ad.html (deflated 66%)
  adding: function_learning/templates/questionnaire.html (deflated 45%)
  adding: function_learning/models.py (deflated 72%)
  adding: function_learning/experiment.py (deflated 61%)
  adding: function_learning/config.txt (deflated 39%)
  adding: function_learning/static/ (stored 0%)
  adding: function_learning/static/scripts/ (stored 0%)
  adding: function_learning/static/scripts/helpers.js (deflated 55%)
  adding: function_learning/static/scripts/raphael-min.js (deflated 65%)
  adding: function_learning/static/scripts/experiment.js (deflated 64%)
  adding: function_learning/static/scripts/mousetrap.min.js (deflated 50%)
  adding: function_learning/static/scripts/mousetrapExtension-pause.min.js (deflated 36%)
  adding: function_learning/static/scripts/bootstrap.min.js (deflated 74%)
  adding: function_learning/static/favicon.ico (deflated 63%)
  adding: function_learning/static/images/ (stored 0%)
  adding: function_learning/static/images/feedback.jpg (deflated 57%)
  adding: function_learning/static/images/logo.png (stored 0%)
  adding: function_learning/static/images/red-bar.jpg (deflated 42%)
  adding: function_learning/static/images/blue-bar.jpg (deflated 49%)
  adding: function_learning/static/images/adjust.jpg (deflated 57%)
  adding: function_learning/static/images/both-bars.jpg (deflated 58%)
  adding: function_learning/static/css/ (stored 0%)
  adding: function_learning/static/css/bootstrap.min.css (deflated 83%)
  adding: function_learning/README.md (deflated 49%)
  adding: function_learning/requirements.txt (stored 0%)
  adding: function_learning/__init__.py (stored 0%)
  adding: vox_populi/ (stored 0%)
  adding: vox_populi/templates/ (stored 0%)
  adding: vox_populi/templates/consent.html (stored 0%)
  adding: vox_populi/templates/instructions/ (stored 0%)
  adding: vox_populi/templates/instructions/instruct-ready.html (deflated 53%)
  adding: vox_populi/templates/layout.html (stored 0%)
  adding: vox_populi/templates/exp.html (deflated 69%)
  adding: vox_populi/templates/ad.html (stored 0%)
  adding: vox_populi/experiment.py (deflated 50%)
  adding: vox_populi/config.txt (deflated 37%)
  adding: vox_populi/static/ (stored 0%)
  adding: vox_populi/static/scripts/ (stored 0%)
  adding: vox_populi/static/scripts/experiment.js (deflated 54%)
  adding: vox_populi/static/scripts/markdown.min.js (deflated 64%)
  adding: vox_populi/static/favicon.ico (deflated 63%)
  adding: vox_populi/static/images/ (stored 0%)
  adding: vox_populi/static/images/logo.png (stored 0%)
  adding: vox_populi/static/css/ (stored 0%)
  adding: vox_populi/static/css/style.css (deflated 21%)
  adding: vox_populi/static/css/bootstrap.min.css (deflated 83%)
  adding: vox_populi/README.md (deflated 10%)
  adding: vox_populi/requirements.txt (stored 0%)
  adding: vox_populi/__init__.py (stored 0%)
  adding: vox_populi/data/ (stored 0%)
  adding: vox_populi/data/None-data/ (stored 0%)
  adding: vox_populi/data/None-data/experiment_id.md (stored 0%)
  adding: snake/ (stored 0%)
  adding: snake/LICENSE.txt (deflated 65%)
  adding: snake/templates/ (stored 0%)
  adding: snake/templates/consent.html (deflated 57%)
  adding: snake/templates/layout.html (deflated 49%)
  adding: snake/templates/exp.html (deflated 47%)
  adding: snake/templates/ad.html (stored 0%)
  adding: snake/templates/instructions.html (deflated 55%)
  adding: snake/experiment.py (deflated 48%)
  adding: snake/config.txt (deflated 38%)
  adding: snake/static/ (stored 0%)
  adding: snake/static/scripts/ (stored 0%)
  adding: snake/static/scripts/experiment.js (deflated 68%)
  adding: snake/static/scripts/store+json2.min.js (deflated 60%)
  adding: snake/static/scripts/atom/ (stored 0%)
  adding: snake/static/scripts/atom/atom.coffee (deflated 68%)
  adding: snake/static/scripts/atom/LICENSE (deflated 47%)
  adding: snake/static/scripts/atom/README.md (deflated 49%)
  adding: snake/static/scripts/atom/atom.js (deflated 72%)
  adding: snake/static/scripts/stake.js (deflated 74%)
  adding: snake/static/scripts/stake.coffee (deflated 66%)
  adding: snake/static/favicon.ico (deflated 63%)
  adding: snake/static/images/ (stored 0%)
  adding: snake/static/images/logo.png (stored 0%)
  adding: snake/static/css/ (stored 0%)
  adding: snake/static/css/bootstrap.min.css (deflated 83%)
  adding: snake/README.md (deflated 30%)
  adding: snake/requirements.txt (stored 0%)
  adding: snake/__init__.py (stored 0%)
  adding: sheep_market/ (stored 0%)
  adding: sheep_market/templates/ (stored 0%)
  adding: sheep_market/templates/consent.html (deflated 55%)
  adding: sheep_market/templates/instructions/ (stored 0%)
  adding: sheep_market/templates/instructions/instruct-ready.html (deflated 55%)
  adding: sheep_market/templates/layout.html (deflated 59%)
  adding: sheep_market/templates/gallery.html (deflated 51%)
  adding: sheep_market/templates/exp.html (deflated 64%)
  adding: sheep_market/templates/ad.html (deflated 40%)
  adding: sheep_market/experiment.py (deflated 55%)
  adding: sheep_market/config.txt (deflated 37%)
  adding: sheep_market/static/ (stored 0%)
  adding: sheep_market/static/scripts/ (stored 0%)
  adding: sheep_market/static/scripts/StackBlur.min.js (deflated 59%)
  adding: sheep_market/static/scripts/raphael-min.js (deflated 65%)
  adding: sheep_market/static/scripts/experiment.js (deflated 57%)
  adding: sheep_market/static/scripts/raphael.sketchpad.min.js (deflated 63%)
  adding: sheep_market/static/scripts/markdown.min.js (deflated 64%)
  adding: sheep_market/static/scripts/drawings.js (deflated 32%)
  adding: sheep_market/static/scripts/canvg.min.js (deflated 75%)
  adding: sheep_market/static/scripts/rgbcolor.min.js (deflated 55%)
  adding: sheep_market/static/favicon.ico (deflated 63%)
  adding: sheep_market/static/images/ (stored 0%)
  adding: sheep_market/static/images/logo.png (stored 0%)
  adding: sheep_market/static/css/ (stored 0%)
  adding: sheep_market/static/css/bootstrap.min.css (deflated 83%)
  adding: sheep_market/README.md (deflated 22%)
  adding: sheep_market/requirements.txt (stored 0%)
  adding: sheep_market/__init__.py (stored 0%)
  adding: sheep_market/data/ (stored 0%)
  adding: sheep_market/data/None-data/ (stored 0%)
  adding: sheep_market/data/None-data/experiment_id.md (stored 0%)
  adding: iterated_drawing/ (stored 0%)
  adding: iterated_drawing/templates/ (stored 0%)
  adding: iterated_drawing/templates/consent.html (deflated 57%)
  adding: iterated_drawing/templates/instructions/ (stored 0%)
  adding: iterated_drawing/templates/instructions/instruct-ready.html (deflated 54%)
  adding: iterated_drawing/templates/layout.html (deflated 57%)
  adding: iterated_drawing/templates/exp.html (deflated 65%)
  adding: iterated_drawing/templates/ad.html (deflated 66%)
  adding: iterated_drawing/models.py (deflated 51%)
  adding: iterated_drawing/experiment.py (deflated 61%)
  adding: iterated_drawing/config.txt (deflated 37%)
  adding: iterated_drawing/static/ (stored 0%)
  adding: iterated_drawing/static/scripts/ (stored 0%)
  adding: iterated_drawing/static/scripts/StackBlur.min.js (deflated 59%)
  adding: iterated_drawing/static/scripts/raphael-min.js (deflated 65%)
  adding: iterated_drawing/static/scripts/experiment.js (deflated 60%)
  adding: iterated_drawing/static/scripts/raphael.sketchpad.min.js (deflated 63%)
  adding: iterated_drawing/static/scripts/markdown.min.js (deflated 64%)
  adding: iterated_drawing/static/scripts/canvg.min.js (deflated 75%)
  adding: iterated_drawing/static/scripts/rgbcolor.min.js (deflated 55%)
  adding: iterated_drawing/static/favicon.ico (deflated 63%)
  adding: iterated_drawing/static/stimuli/ (stored 0%)
  adding: iterated_drawing/static/stimuli/owl.png (deflated 6%)
  adding: iterated_drawing/static/images/ (stored 0%)
  adding: iterated_drawing/static/images/logo.png (stored 0%)
  adding: iterated_drawing/static/css/ (stored 0%)
  adding: iterated_drawing/static/css/bootstrap.min.css (deflated 83%)
  adding: iterated_drawing/README.md (deflated 45%)
  adding: iterated_drawing/requirements.txt (stored 0%)
  adding: iterated_drawing/bartlett-drawing.jpg (deflated 36%)
  adding: iterated_drawing/__init__.py (stored 0%)
  adding: iterated_drawing/data/ (stored 0%)
  adding: iterated_drawing/data/None-data/ (stored 0%)
  adding: iterated_drawing/data/None-data/experiment_id.md (stored 0%)
  adding: chatroom/ (stored 0%)
  adding: chatroom/templates/ (stored 0%)
  adding: chatroom/templates/consent.html (deflated 57%)
  adding: chatroom/templates/layout.html (deflated 47%)
  adding: chatroom/templates/exp.html (deflated 54%)
  adding: chatroom/templates/ad.html (stored 0%)
  adding: chatroom/templates/instructions.html (deflated 54%)
  adding: chatroom/experiment.py (deflated 64%)
  adding: chatroom/config.txt (deflated 39%)
  adding: chatroom/static/ (stored 0%)
  adding: chatroom/static/scripts/ (stored 0%)
  adding: chatroom/static/scripts/experiment.js (deflated 69%)
  adding: chatroom/static/scripts/store+json2.min.js (deflated 60%)
  adding: chatroom/static/favicon.ico (deflated 63%)
  adding: chatroom/static/images/ (stored 0%)
  adding: chatroom/static/images/logo.png (stored 0%)
  adding: chatroom/static/css/ (stored 0%)
  adding: chatroom/static/css/bootstrap.min.css (deflated 83%)
  adding: chatroom/README.md (deflated 34%)
  adding: chatroom/requirements.txt (stored 0%)
  adding: chatroom/__init__.py (stored 0%)
  adding: chatroom/data/ (stored 0%)
  adding: chatroom/data/wa6bcff75-4809-45c8-b56a-2c97-data/ (stored 0%)
  adding: chatroom/data/wa6bcff75-4809-45c8-b56a-2c97-data/README.txt (stored 0%)
  adding: concentration/ (stored 0%)
  adding: concentration/templates/ (stored 0%)
  adding: concentration/templates/consent.html (deflated 53%)
  adding: concentration/templates/layout.html (deflated 58%)
  adding: concentration/templates/exp.html (deflated 78%)
  adding: concentration/templates/ad.html (stored 0%)
  adding: concentration/templates/instructions.html (deflated 54%)
  adding: concentration/LICENSE (stored 0%)
  adding: concentration/experiment.py (deflated 49%)
  adding: concentration/config.txt (deflated 40%)
  adding: concentration/static/ (stored 0%)
  adding: concentration/static/scripts/ (stored 0%)
  adding: concentration/static/scripts/experiment.js (deflated 67%)
  adding: concentration/static/scripts/store+json2.min.js (deflated 60%)
  adding: concentration/static/scripts/memory.js (deflated 72%)
  adding: concentration/static/scripts/classList.min.js (deflated 54%)
  adding: concentration/static/favicon.ico (deflated 63%)
  adding: concentration/static/images/ (stored 0%)
  adding: concentration/static/images/logo.png (stored 0%)
  adding: concentration/static/images/default/ (stored 0%)
  adding: concentration/static/images/default/monsters-14.png (deflated 9%)
  adding: concentration/static/images/default/monsters-03.png (deflated 2%)
  adding: concentration/static/images/default/monsters-01.png (deflated 4%)
  adding: concentration/static/images/default/monsters-12.png (deflated 3%)
  adding: concentration/static/images/default/monsters-13.png (deflated 2%)
  adding: concentration/static/images/default/monsters-16.png (deflated 2%)
  adding: concentration/static/images/default/monsters-07.png (deflated 3%)
  adding: concentration/static/images/default/monsters-15.png (deflated 3%)
  adding: concentration/static/images/default/monsters-10.png (deflated 2%)
  adding: concentration/static/images/default/monsters-11.png (deflated 4%)
  adding: concentration/static/images/default/monsters-05.png (deflated 1%)
  adding: concentration/static/images/default/logo-bw.png (stored 0%)
  adding: concentration/static/images/default/monsters-02.png (deflated 4%)
  adding: concentration/static/images/default/monsters-04.png (deflated 6%)
  adding: concentration/static/images/default/monsters-08.png (deflated 4%)
  adding: concentration/static/images/default/monsters-06.png (deflated 8%)
  adding: concentration/static/images/default/monsters-09.png (deflated 2%)
  adding: concentration/static/images/og-image.png (deflated 2%)
  adding: concentration/static/css/ (stored 0%)
  adding: concentration/static/css/memory.css (deflated 76%)
  adding: concentration/static/css/bootstrap.min.css (deflated 83%)
  adding: concentration/README.md (deflated 30%)
  adding: concentration/requirements.txt (stored 0%)
  adding: concentration/screenshot.jpg (deflated 49%)
  adding: concentration/__init__.py (stored 0%)
Making 'bartlett1932' demo...
Making 'mcmcp' demo...
Making 'rogers' demo...
Making 'twentyfortyeight' demo...
Making 'function_learning' demo...
Making 'vox_populi' demo...
Making 'snake' demo...
Making 'sheep_market' demo...
Making 'iterated_drawing' demo...
Making 'chatroom' demo...
Making 'concentration' demo...
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dallinger/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dallinger/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dallinger/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dallinger/envs/latest/local/lib/python2.7/site-packages/sphinx/registry.py", line 318, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension sphinx_js (exception: No module named sphinx_js)

Extension error:
Could not import extension sphinx_js (exception: No module named sphinx_js)
```

The latest "latest" branch build fails with the same error as then:
https://readthedocs.org/projects/dallinger/builds/7675359/

**Comment by alecpm** [comment]
We need to ensure that Read The Docs installs `dev-requirements.txt`, and probably also node packages from `package.json`. I think we may be able to use a [`readthedocs.yml`](https://docs.readthedocs.io/en/latest/yaml-config.html) like this:

    # .readthedocs.yml
    
    build:
      image: latest
    
    python:
      version: 3.6
    
    requirements_file: dev-requirements.txt

Not sure how to manage the node package installation, that might happen automatically or else we may need a conda configuration file.

**Comment by cguardia** [comment]
The solution recommended by @alecpm did the trick.
PR: https://github.com/Dallinger/Dallinger/pull/1364

**Comment by witekdev** [comment]
Verified to be working
