### ISSUE TITLE
Error running on mturk sandbox: KeyError: 'heroku_team'

### ISSUE THREAD

**Issue by mmosleh** [Dallinger/Dallinger#1317]
I have just pulled the most recent version of Dallinger from github and want to run a sandbox test for bartlett1932 demo. I have already logged in into Heroku. However, I receive the following error.

(dallinger) user-MacBook-Pro:twentyfortyeight CurrentUser$ dallinger sandbox --verbose

Does it work with free dyno on Heroku at all?
```
                                   v4.0.0

                Laboratory automation for
       the behavioral and social sciences.

Traceback (most recent call last):
  File "/Users/CurrentUser/.virtualenvs/dallinger/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/Users/CurrentUser/.virtualenvs/dallinger/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/CurrentUser/.virtualenvs/dallinger/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/CurrentUser/.virtualenvs/dallinger/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/CurrentUser/.virtualenvs/dallinger/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/CurrentUser/.virtualenvs/dallinger/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/CurrentUser/Documents/Dallinger/dallinger/command_line.py", line 112, in wrapper
    result = func(*args, **kwargs)
  File "/Users/CurrentUser/Documents/Dallinger/dallinger/command_line.py", line 320, in sandbox
    _deploy_in_mode('sandbox', app=app, verbose=verbose, log=log)
  File "/Users/CurrentUser/Documents/Dallinger/dallinger/deployment.py", line 355, in _deploy_in_mode
    deploy_sandbox_shared_setup(log, verbose=verbose, app=app)
  File "/Users/CurrentUser/Documents/Dallinger/dallinger/deployment.py", line 228, in deploy_sandbox_shared_setup
    heroku.sanity_check(config)
  File "/Users/CurrentUser/Documents/Dallinger/dallinger/heroku/tools.py", line 524, in sanity_check
    team = config.get('heroku_team').strip() or None
  File "/Users/CurrentUser/Documents/Dallinger/dallinger/config.py", line 152, in get
    raise KeyError(key)
KeyError: 'heroku_team'
```

## Expected Behavior
get connected to heroku and launch the Hit on mturk sandbox

## Current Behavior
receive an error described above

## Steps to Reproduce (for bugs)
1. pull the most recent version of Dallinger from Github and follow developer installation instruction
2. log in into Heroku
3. run dallinger sandbox --verbose on a demo folder

## Context
can't test the platform as a new user

## Your Environment

* Dallinger version used:
v4.0.0
* Operating System and version (desktop or mobile):
desktop 
* Browser and version (e.g. Chrome 39, node.js 5.4):
Chrome
macOs
* Link to your project:

**Comment by jessesnyder** [comment]
@alecpm It looks like we need to switch the `None` (or `''`?) to being the default inside the call to `config.get('heroku_team')`. Missed this since our test harness always has the key defined.

**Comment by alecpm** [comment]
Indeed, I'll make a quick PR for this.
