### ISSUE TITLE
Heroku - Make sure demos can run on the free tier

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1326]
Dallinger demos as configured on master, should work out of the box.

In the process of testing https://github.com/Dallinger/Dallinger/pull/1322
I disabled my heroku_team setting and tried to run bartlett with its default config.txt

I got this traceback:
```
Buildpack added. Next release on dlgr-4a89811d will use:
  1. heroku/python
  2. https://github.com/stomita/heroku-buildpack-phantomjs
Run git push heroku master to create a new release using these buildpacks.
Creating heroku-postgresql:standard-0 on ⬢ dlgr-4a89811d... !
 ▸    Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at
 ▸    https://heroku.com/verify
Traceback (most recent call last):
  File "/home/witek/.virtualenvs/Dallinger/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/home/witek/.virtualenvs/Dallinger/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/witek/.virtualenvs/Dallinger/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/witek/.virtualenvs/Dallinger/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/witek/.virtualenvs/Dallinger/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/witek/.virtualenvs/Dallinger/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/command_line.py", line 112, in wrapper
    result = func(*args, **kwargs)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/command_line.py", line 320, in sandbox
    _deploy_in_mode('sandbox', app=app, verbose=verbose, log=log)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/deployment.py", line 355, in _deploy_in_mode
    deploy_sandbox_shared_setup(log, verbose=verbose, app=app)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/deployment.py", line 272, in deploy_sandbox_shared_setup
    heroku_app.addon(name)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/heroku/tools.py", line 127, in addon
    self._run(cmd)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/heroku/tools.py", line 44, in _run
    return check_call(cmd, stdout=self.out)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/utils.py", line 147, in wrapper
    return func(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['heroku', 'addons:create', 'heroku-postgresql:standard-0', '--app', 'dlgr-4a89811d']' returned non-zero exit status 1.
(Dallinger) witek@ubuntu:~/dev/jazkarta/Dallinger/demos/dlgr/demos/bartlett1932$
```

Bartlett config.txt
```
[Experiment]
mode = sandbox
auto_recruit = true
webdriver_type = phantomjs

[MTurk]
title = War of the Ghosts
description = Read a brief story and answer some questions about it.
keywords = Psychology, reading, text
base_payment = 1.00
lifetime = 24
duration = 0.1
us_only = true
approve_requirement = 95
contact_email_on_error = bartlett1932@mailinator.com
ad_group = War of the Ghosts
organization_name = Monsters University
browser_exclude_rule = MSIE, mobile, tablet

[Database]
database_url = postgresql://postgres@localhost/dallinger
database_size = standard-0

[Server]
dyno_type = free
num_dynos_web = 1
num_dynos_worker = 1
host = 0.0.0.0
notification_url = None
clock_on = false
logfile = -
```

**Comment by MatthewWilkes** [comment]
I think this is a duplicate of #106

**Comment by witekdev** [comment]
Related https://github.com/Dallinger/Dallinger/issues/343

**Comment by witekdev** [comment]
Documentation as to what is required to run the demos on Heroku has been included in this PR: https://github.com/Dallinger/Dallinger/pull/1372

**Comment by witekdev** [comment]
This has been documentated here: http://docs.dallinger.io/en/latest/demo_index.html
