### ISSUE TITLE
MTurkServiceException

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#1398]
I was running a GU game and saw the following traceback in the logs:

```
Sep 23 15:18:09 dlgr-b96f5d8e app/worker.1:  Traceback (most recent call last): 
Sep 23 15:18:09 dlgr-b96f5d8e app/worker.1:    File "/app/.heroku/src/dallinger/dallinger/mturk.py", line 525, in approve_assignment 
Sep 23 15:18:09 dlgr-b96f5d8e app/worker.1:      self.mturk.approve_assignment(AssignmentId=assignment_id) 
Sep 23 15:18:09 dlgr-b96f5d8e app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call 
Sep 23 15:18:09 dlgr-b96f5d8e app/worker.1:      return self._make_api_call(operation_name, kwargs) 
Sep 23 15:18:09 dlgr-b96f5d8e app/worker.1:    File "/app/.heroku/python/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call 
Sep 23 15:18:09 dlgr-b96f5d8e app/worker.1:      raise error_class(parsed_response, operation_name) 
Sep 23 15:18:09 dlgr-b96f5d8e app/worker.1:  botocore.errorfactory.RequestError: An error occurred (RequestError) when calling the ApproveAssignment operation: This operation can be called with a status of: Submitted (1537741087056) 
```

**Comment by suchow** [comment]
yes, yes

**Comment by MatthewWilkes** [comment]
This looks similar to one of the issues I identified in my paste of live problems I saw. In that case, an earlier transition failed.

**Comment by jessesnyder** [comment]
@a-paxton Also running into this bug. Annotated log excerpt attached.
[DallingerApproveAssignmentErrorAnnotated.txt](https://github.com/Dallinger/Dallinger/files/2531387/DallingerApproveAssignmentErrorAnnotated.txt)

**Comment by jessesnyder** [comment]
AssignmentSubmitted messages sent to MTurk, with failures marked:
```

Oct 30 11:55:45 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 37QW5D2ZRHFGODA9QIUM6O5EETSS8O 
Oct 30 11:56:18 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 39PAAFCODNTFEPJ1NBAM87L8RA7TVJ FAILED
Oct 30 11:56:21 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 39PAAFCODNTFEPJ1NBAM87L8RA7TVJ 
Oct 30 11:59:01 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3FE7TXL1LJGTPIT7IXWG1XDAA5G2Q7 
Oct 30 11:59:13 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 3ZV9H2YQQE0NUXLCY69RCW0O4KX3WN 
Oct 30 12:00:23 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3GGAI1SQEWRF2LNHNXE5W12RCVVCM2 
Oct 30 12:00:52 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3ZAZR5XV02BF1SM02M4Z43Y0RZDCZJ 
Oct 30 12:00:58 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 3ZAZR5XV02BF1SM02M4Z43Y0RZDCZJ 
Oct 30 12:01:03 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 3ZAZR5XV02BF1SM02M4Z43Y0RZDCZJ 
Oct 30 12:01:19 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 352YTHGROW6QF39R3LSALYI73WF4H8 
Oct 30 12:01:19 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 3IJXV6UZ1YCXC4M9KF68T3UWVNEIRY 
Oct 30 12:01:19 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 32ZKVD547GGV6UN13FDVPIN3UJFB3F 
Oct 30 12:01:20 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3ZSY5X72NY478QXCIAJDD0QI7WDRO2 
Oct 30 12:01:20 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3JZQSN0I3R3MDNB53W6BR23XDMBGF9 
Oct 30 12:01:20 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3TAYZSBPLM152Y8KA1LLWXSBST02SV 
Oct 30 12:01:21 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3SEPORI8WOSR8DP2I888Y88CRWSZA4 
Oct 30 12:01:21 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 39GAF6DQWSTE557SLSQC212DZRH1VJ 
Oct 30 12:01:21 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3J88R45B2HR9QMVP692KRIHWIIUXPL 
Oct 30 12:01:32 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3EFE17QCRDY9HOB2TMOSJ1YDHCHSH2 
Oct 30 12:01:32 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3KXIR214I59M0D69K0P3YUC5EDY24P 
Oct 30 12:01:32 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3ZSY5X72NY478QXCIAJDD0QI7WDORZ 
Oct 30 12:01:32 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 33LK57MYLUYV89BWZ8UZJ82ID2ZZS0 
Oct 30 12:01:33 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3IJXV6UZ1YCXC4M9KF68T3UWVNERI7 
Oct 30 12:01:33 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3M23Y66PO30TKZRLX3XOMA9N8Y36SH 
Oct 30 12:01:33 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3PS7W85Z80VHHI6YKA5QGPWB0IO9TJ 
Oct 30 12:01:33 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3C2NJ6JBKBA8MLGF254ZX3I55UT2NK 
Oct 30 12:01:34 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 33M4IA01QHUU2ZB4J169WDHBJ0HXRC 
Oct 30 12:01:34 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3PXX5PX6LYRVQFMMCUS5CQ190T6BAA 
Oct 30 12:01:34 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3ATPCQ38J93R3NFXMM6PK1ZAL2PAYP 
Oct 30 12:01:34 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3NVC2EB65RSRJ2GCD7RFXTL4FSWY3G 
Oct 30 12:01:45 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 30LB5CDZND3V70RKQ6BF92WZIAG0ZE 
Oct 30 12:01:45 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3Q8GYXHFEQVHUE2BVYXJFZR5Q055C5 
Oct 30 12:01:45 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3X31TUMD7YFB90VY7OO6FS4B8TF1L0 
Oct 30 12:01:45 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3FTF2T8WLSB99ZASFFA1393A4C6W9W 
Oct 30 12:01:45 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3WYGZ5XF3X80JECAZ7RPWTE59TLSK6 
Oct 30 12:01:46 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3R6BYFZZP85XZ96VS66FFO3SGC8FX1 
Oct 30 12:01:46 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3TOK3KHVJUBXQ7DX9WL78JZI6KJO70 
Oct 30 12:01:46 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3Y9N9SS8LZ4OLRLLHB41K8B3X4Q3DD 
Oct 30 12:01:46 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3CTOC39K38JJPWM0TJT20NIW7QBJ7E 
Oct 30 12:01:52 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3JJVG1YBECQYK9A5HY1O4FLN8F55BY 
Oct 30 12:02:18 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3BWI6RSP7H2BEG08FIIB37542IDE7M FAILED
Oct 30 12:02:18 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3NPI0JQDAPY295M51Z1N2FWQ5M6PTU 
Oct 30 12:02:19 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 33LKR6A5KFDZSD33GXQX1JES260T1U 
Oct 30 12:02:19 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 38F5OAUN5O5NYQRA5JQHOA2HUY67HW 
Oct 30 12:02:19 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3R2PKQ87NX16FO9HF7AR740MP0GMIF 
Oct 30 12:02:19 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 30BXRYBRP5Q2O5SBDRYTGQ1YNPEHW7 
Oct 30 12:02:19 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 37ZHEEHM6XF84IKBQY1FKG17BTN73O 
Oct 30 12:02:22 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3W8CV64QJ3SRC9F3KGO126TNPOU9HA 
Oct 30 12:02:29 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3B2X28YI3X8U3DAJMHBTWLZN4AHB6L 
Oct 30 12:02:41 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3R5F3LQFV3DGAHJ3SRDQZ3SHGDWOZS 
Oct 30 12:02:41 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3DY46V3X3QBWVTTWGOAB1TLVYJK55Y 
Oct 30 12:03:07 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3HYA4D452SCWYT3Y4HLMPY9W337F2Q 
Oct 30 12:03:59 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 31EUONYN2WWZ1XETRUONEXFLS2QOVS 
Oct 30 12:05:09 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3MTMREQS4WBNEIKX7LO1Z4EUAUPAWQ FAILED
Oct 30 12:05:51 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 32Q90QCQ1TEZ9V7SYC7K7CAQ82EEKT 
Oct 30 12:06:06 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3HMIGG0U4MZDKZMIPOMBOATFVEO8YI FAILED
Oct 30 12:06:17 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3NVC2EB65RSRJ2GCD7RFXTL4FSVY3F 
Oct 30 12:06:32 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3COPXFW7XC536MWI7QNV1O9UM9FKPJ 
Oct 30 12:07:03 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 30OG32W0SV40H1SVVPZ0Z4RU2XJENY 
Oct 30 12:07:21 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3TUI152ZZCGM0XBBZTW2WE35IZ0Q1C 
Oct 30 12:07:21 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 39ASUFLU6Y05TV6ZXVM9X6IS4BTEXI 
Oct 30 12:08:12 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3Y4W8Q93L0D8X0N41LA7333MOOJVD2 FAILED
Oct 30 12:08:25 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3MB8LZR5BGMDF1HKFYUOK70AHZGLKO 
Oct 30 12:09:41 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3OONKJ5DKDCKSJGNMDXNDLLEPACOBO 
Oct 30 12:10:15 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3TE3O857311T1J87VCLG6NNF6RKR2Z 
Oct 30 12:11:23 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3X1FV8S5JYKB9KXV3BBF9O6J1GYVGB 
Oct 30 12:11:23 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3S3AMIZX3VYCYRH4A4F2DBFX3H5CDM 
Oct 30 12:11:42 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3EFVCAY5L42NPARJ3OL8ENERIAIJ82 
Oct 30 12:12:11 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3TPZPLC3M15XAOOBMKVWK2SSBNWP3G 
Oct 30 12:12:23 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3ZDAD0O1T267IEOWNQB4WSIT7LFTXM 
Oct 30 12:12:28 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3EFVCAY5L42NPARJ3OL8ENERIAHJ81 
Oct 30 12:12:28 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3S3AMIZX3VYCYRH4A4F2DBFX3H3CDK 
Oct 30 12:13:13 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3FE7TXL1LJGTPIT7IXWG1XDAA5F2Q6 
Oct 30 12:13:21 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3GGAI1SQEWRF2LNHNXE5W12RCVVMCC 
Oct 30 12:13:42 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 31N2WW6R9SJLJBZH8HZR88EO9H6F30 
Oct 30 12:14:36 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 336KAV9KYRL2YKKT97DAEJGC9E12YE 
Oct 30 12:15:07 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3IUZPWIU1P0TQVTJJC1QTIHQF6NKWJ FAILED
Oct 30 12:15:07 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3DZQRBDBSM8UNG43E1ZQF7X3Y76S32 FAILED
Oct 30 12:15:17 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 31N2WW6R9SJLJBZH8HZR88EO9HD3FV 
Oct 30 12:16:21 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3FDJT1UU751ZDCEZNBEH3I4DV9H5KL 
Oct 30 12:19:24 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3AMW0RGHOEV4ESHL43FBTGQYG4SPN1 
Oct 30 12:19:24 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3570Y55XZQCSDES08MYZGNADJX7YGU 
Oct 30 12:19:24 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3DY46V3X3QBWVTTWGOAB1TLVYJJ55X 
Oct 30 12:19:31 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3GFK2QRXXAAQ8C8GCPXKRTY8IGN5WE 
Oct 30 12:19:53 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3FIUS151DWVSRN70EGCT9N39E1BGG8 
Oct 30 12:20:17 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3M68NM076I0HJKR8IEXJW04RMWOR6I 
Oct 30 12:20:18 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 36PW28KO40PTXIY6MLUVDY7U3RSAEK FAILED
Oct 30 12:20:21 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 36WLNQG7803YGS3YSZUR89R0L84EB8 
Oct 30 12:26:29 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3RWE2M8QWI31QBD1NI0LEFPQ8W80NX 
Oct 30 12:26:33 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3FFJ6VRIL2H9CA2AQ2NT97T9MXE0IH 
Oct 30 12:27:00 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3907X2AHF1Y8P6SSIKHR1SN05A62PU 
Oct 30 12:27:29 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3M68NM076I0HJKR8IEXJW04RMWJR6D 
Oct 30 12:27:32 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3RKNTXVS3NRB5G1DXFII4CV3Q1QA44 
Oct 30 12:27:39 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3TS1AR6UQR73KU04AT2HLPQ4EJT7FY 
Oct 30 12:30:27 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3TOK3KHVJUBXQ7DX9WL78JZI6KJ7OJ 
Oct 30 12:36:17 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3VELCLL3GLCP98L2LDL8KFZRBXTF19 
Oct 30 12:37:11 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3URFVVM166BBNM30ODPZY9K6YZJUZA FAILED
Oct 30 12:43:24 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3IX2EGZR7CCT7F6F2XR8549W83NRJ5 
Oct 30 12:44:04 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 31EUONYN2WWZ1XETRUONEXFLS39OVD FAILED
Oct 30 12:44:41 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3QUO65DNQVHZOIPTM4EIIBD2EVIOU4 
Oct 30 12:45:03 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3WYGZ5XF3X80JECAZ7RPWTE59U7SKU 
Oct 30 12:45:29 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3E13VNJ1NOO9JZNSMLRTNCCJRPM1IN 
Oct 30 12:47:36 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3YDTZAI2WY9FBSOD1WPPTB20M7K41A 
Oct 30 12:47:37 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3T111IHZ5FJ413T6GL0VGAVTCXR9R6 
Oct 30 12:48:29 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3E4GGUZ1T9K7EFVC5SCJ5B11B06K2H 
Oct 30 12:59:10 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3OXV7EAXLFJP0I667OWNE21BGI336L 
Oct 30 12:59:33 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3GLB5JMZFYOPF3X9CQBL320C1ACGDH 
Oct 30 13:02:06 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3IO1LGZLKAQB1FCCJ5RJ5J9MW5Q68D FAILED
Oct 30 13:08:44 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3O6CYIULEEU7TRYVDQ5SZ5QOHY9UWG 
Oct 30 13:09:43 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3C5W7UE9CGJ35JYCETASAEN1DE6XME 
Oct 30 13:09:54 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3J2UYBXQQM5TJQ79O1E4C434D7D06J 
Oct 30 13:10:47 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3NOKK93PR21WNVFI2QWH9HXLO69EE2 
Oct 30 13:10:49 dlgr-b2f039cb app/worker.2:  AssignmentSubmitted notification for assignment 3NOKK93PR21WNVFI2QWH9HXLO69EE2 
Oct 30 13:15:11 dlgr-b2f039cb app/worker.1:  AssignmentSubmitted notification for assignment 3P529IW9KZE2ZFP6EN3R4U8594PLFE FAILED
Oct 30 13:15:11 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3KB8R4ZV1F0W06ZPYUKF8CCCYPGGBQ FAILED
Oct 30 13:20:14 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3LKC68YZ3BWCGMEYH4TJ0ZYZZCRWOB 
Oct 30 13:20:45 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 3PEIJLRY6UMZAVSQIVGFJCPSBGUWXE 
Oct 30 13:23:54 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 3OF2M9AATHHXKQYOUZLXSMB8W8NKZ5 
Oct 30 13:39:42 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3HQUKB7LNG7KRFXMISCTFNRB83DHHN 
Oct 30 13:40:42 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 3907X2AHF1Y8P6SSIKHR1SN05B5P2I 
Oct 30 13:50:39 dlgr-b2f039cb app/worker.1: AssignmentSubmitted notification for assignment 3JC6VJ2SACCT1Z5DBK1S941HQYL5A6 
Oct 30 13:51:25 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 36DSNE9QZ6RQA2EZA5A4B94RXGPJOA 
Oct 30 14:10:05 dlgr-b2f039cb app/worker.2: AssignmentSubmitted notification for assignment 36PW28KO40PTXIY6MLUVDY7U3RQAEI FAILED
```
