### ISSUE TITLE
Can we capture the output of subprocess.check_call() in our GitClient?

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#1403]
Failure output is currently useless. Debugging requires locating the generated temp directory and running git commands there locally to get useful error message. 

Reported by Thomas Langlois in Slack:
```
❯❯ Pushing code to Heroku...
Traceback (most recent call last):
 File "/home/thomas/.local/bin/dallinger", line 11, in <module>
   sys.exit(dallinger())
 File "/home/thomas/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
   return self.main(*args, **kwargs)
 File "/home/thomas/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
   rv = self.invoke(ctx)
 File "/home/thomas/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/thomas/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/home/thomas/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/home/thomas/.local/lib/python2.7/site-packages/dallinger/command_line.py", line 566, in deploy
   _deploy_in_mode(u'live', app, verbose)
 File "/home/thomas/.local/lib/python2.7/site-packages/dallinger/command_line.py", line 550, in _deploy_in_mode
   deploy_sandbox_shared_setup(verbose=verbose, app=app)
 File "/home/thomas/.local/lib/python2.7/site-packages/dallinger/command_line.py", line 504, in deploy_sandbox_shared_setup
   git.push(remote="heroku", branch="HEAD:master")
 File "/home/thomas/.local/lib/python2.7/site-packages/dallinger/utils.py", line 52, in push
   self._run(cmd)
 File "/home/thomas/.local/lib/python2.7/site-packages/dallinger/utils.py", line 55, in _run
   subprocess.check_call(cmd, stdout=self.out, stderr=self.out)
 File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
   raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'heroku', 'HEAD:master']' returned non-zero exit status 1
```

**Comment by jessesnyder** [comment]
This is already implemented on master and in v5.0.0. Not sure what version the bug report relates to.
