### ISSUE TITLE
Read the docs are not updating to reflect documentation updates

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1607]
Normally when the documentation updates have been merged to the master branch, the docs would automatically rebuild themselves. Somehow that is not working anymore. :(

https://readthedocs.org/projects/dallinger/

**Comment by suchow** [comment]
This might be relevant, though the dates don't match up:

> Hello!
> --
> Your project, Dallinger, is currently using GitHub Services to trigger builds on Read the Docs. Effective January 31, 2019, GitHub will no longer process requests using the Services feature, and so Read the Docs will not receive notifications on updates to your repository.To continue building your Read the Docs project on changes to your repository, you will need to add a new webhook on your GitHub repository. You can either connect your GitHub account and configure a GitHub webhook integration, or you can add a generic webhook integration.You can find more information on our webhook intergrations in our documentation, at:https://docs.readthedocs.io/en/latest/webhooks.html#webhook-github-services
> 
> Keep documenting,
> Read the Docs
>

**Comment by witekdev** [comment]
The webhook has been updated/fixed. Latest docs are live.

**Comment by jessesnyder** [comment]
Seems related to #3447 
Latest build traceback is at https://readthedocs.org/projects/dallinger/builds/15165802/
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dallinger/envs/latest/lib/python3.8/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dallinger/checkouts/latest/docs/source/conf.py", line 84, in <module>
    from dallinger.version import __version__ as version
  File "/home/docs/checkouts/readthedocs.org/user_builds/dallinger/checkouts/latest/dallinger/__init__.py", line 3, in <module>
    from . import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/dallinger/checkouts/latest/dallinger/bots.py", line 23, in <module>
    "phantomjs": webdriver.PhantomJS,
AttributeError: module 'selenium.webdriver' has no attribute 'PhantomJS'
```

**Comment by jessesnyder** [comment]
@jacobyn This is still a problem. The latest docs on readthedocs are for v7.6.0, released in August 2021.
