### ISSUE TITLE
Redis error when trying to run experiment on sandbox

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1671]
```
Traceback (most recent call last):
  File "/home/witek/.virtualenvs/dlgr_env2.7/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/home/witek/.virtualenvs/dlgr_env2.7/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/witek/.virtualenvs/dlgr_env2.7/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/witek/.virtualenvs/dlgr_env2.7/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/witek/.virtualenvs/dlgr_env2.7/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/witek/.virtualenvs/dlgr_env2.7/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/command_line.py", line 290, in wrapper
    return f(**kwargs)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/command_line.py", line 126, in wrapper
    result = func(*args, **kwargs)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/command_line.py", line 392, in sandbox
    _deploy_in_mode('sandbox', app=app, verbose=verbose, log=log)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/deployment.py", line 378, in _deploy_in_mode
    deploy_sandbox_shared_setup(log, verbose=verbose, app=app)
  File "/home/witek/dev/jazkarta/Dallinger/dallinger/deployment.py", line 313, in deploy_sandbox_shared_setup
    r = redis.from_url(heroku_app.redis_url)
  File "/home/witek/.virtualenvs/dlgr_env2.7/local/lib/python2.7/site-packages/redis/utils.py", line 19, in from_url
    return Redis.from_url(url, db, **kwargs)
  File "/home/witek/.virtualenvs/dlgr_env2.7/local/lib/python2.7/site-packages/redis/client.py", line 602, in from_url
    connection_pool = ConnectionPool.from_url(url, db=db, **kwargs)
  File "/home/witek/.virtualenvs/dlgr_env2.7/local/lib/python2.7/site-packages/redis/connection.py", line 920, in from_url
    'schemes (%s)' % valid_schemes)
ValueError: Redis URL must specify one of the followingschemes (redis://, rediss://, unix://)
```

This was introduced by https://github.com/Dallinger/Dallinger/pull/1660

Specifically 
### 3.1.0
```
* Connection URLs must have one of the following schemes:
   redis://, rediss://, unix://. Thanks jdupl123. 961/969
```

**Comment by witekdev** [comment]
@jessesnyder would our tests not pickup something like this?

**Comment by jessesnyder** [comment]
@witekdev We test our local Redis connection:
```
redis_url = os.getenv('REDIS_URL', 'redis://localhost:6379')
redis_conn = redis.from_url(redis_url)
```
... but the problem above is with a connection to redis on heroku. We determine the redis URL by calling `heroku config:get REDIS_URL --app [app name]`, and that must use a different scheme.

**Comment by witekdev** [comment]
@jessesnyder ah ok, makes sense.

**Comment by jessesnyder** [comment]
It would be interesting to see what URL heroku is returning. Their docs show URLS that start with `redis://`: https://devcenter.heroku.com/articles/heroku-redis

**Comment by witekdev** [comment]
(Pdb) heroku_app.redis_url
u'redis://h:p8bcb81a19aaad5c46b296db55a3f75aa1af075845fc5c2f20d1345af0372efa3@ec2-35-153-174-124.compute-1.amazonaws.com:27429\n'

**Comment by witekdev** [comment]
I cant seem to reproduce this error, however I see that running sandbox uses redis 3.0.1:
```
❯ Saving the URL of the postgres database...
[master 2d58a30] "Save URLs for database and notifications"
 1 file changed, 6 insertions(+), 1 deletion(-)
GitClient: "git add config.txt"GitClient: "git commit -m "Save URLs for database and notifications""
❯❯ Pushing code to Heroku...
remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> Python app detected        
remote:  !     Python has released a security update! Please consider upgrading to python-3.6.8        
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes        
remote: -----> Installing python-3.6.6        
remote: -----> Installing pip        
remote: -----> Installing SQLite3        
remote: -----> Installing requirements with pip        
remote:        Collecting dallinger==5.0.5 (from -r /tmp/build_f0272dbc30e2f0c0ea18d27f21a56e52/requirements.txt (line 1))        
remote:          Downloading https://files.pythonhosted.org/packages/36/08/22ca380c12f69ec3e6788cce24ac32513240d0016ade2ca5248ba324a860/dallinger-5.0.5.tar.gz (1.5MB)        
remote:        Collecting redis==3.0.1 (from dallinger==5.0.5->-r /tmp/build_f0272dbc30e2f0c0ea18d27f21a56e52/requirements.txt (line 1))        
remote:          Downloading https://files.pythonhosted.org/packages/f5/00/5253aff5e747faf10d8ceb35fb5569b848cde2fdc13685d42fcf63118bbc/redis-3.0.1-py2.py3-none-any.whl (61kB)
```

**Comment by witekdev** [comment]
Managed to reproduce, complete traceback:
```
(dlgr_env) witek@ubuntu:~/Dallinger/demos/dlgr/demos/bartlett1932$ dallinger sandbox --verbose
✓ config.txt is PRESENT
✓ experiment.py is PRESENT

    ____        ____
   / __ \____ _/ / (_)___  ____ ____  _____
  / / / / __ `/ / / / __ \/ __ `/ _ \/ ___/
 / /_/ / /_/ / / / / / / / /_/ /  __/ /
/_____/\__,_/_/_/_/_/ /_/\__, /\___/_/
                        /____/
                                   v5.0.5

                Laboratory automation for
       the behavioral and social sciences.


❯❯ Experiment id is b46ab9b3-04ee-77a1-0a9c-8b971fe371ad
/tmp/tmprbXVwu/b46ab9b3-04ee-77a1-0a9c-8b971fe371ad

❯❯ Freezing the experiment package...

❯❯ Making sure that you are logged in to Heroku.
 ›   Warning: token will expire 02/22/2020
 ›   Use heroku authorizations:create to generate a long-term token

Initialized empty Git repository in /tmp/tmprbXVwu/b46ab9b3-04ee-77a1-0a9c-8b971fe371ad/.git/
[master (root-commit) dc84e4b] ""Experiment b46ab9b3-04ee-77a1-0a9c-8b971fe371ad""
 50 files changed, 1947 insertions(+)
 create mode 100644 Procfile
 create mode 100644 README.md
 create mode 100644 __init__.py
 create mode 100644 __init__.pyc
 create mode 100644 config.txt
 create mode 100644 demo.ipynb
 create mode 100644 experiment.py
 create mode 100644 experiment.pyc
 create mode 100644 experiment_id.txt
 create mode 100644 models.py
 create mode 100644 requirements.txt
 create mode 100644 runtime.txt
 create mode 100644 static/css/bootstrap.min.css
 create mode 100644 static/css/dallinger.css
 create mode 100644 static/favicon.ico
 create mode 100644 static/images/logo.png
 create mode 100644 static/robots.txt
 create mode 100644 static/scripts/dallinger2.js
 create mode 100644 static/scripts/experiment.js
 create mode 100644 static/scripts/markdown.min.js
 create mode 100644 static/scripts/reconnecting-websocket.js
 create mode 100644 static/scripts/require.js
 create mode 100755 static/scripts/reqwest.min.js
 create mode 100644 static/scripts/spin.min.js
 create mode 100644 static/scripts/store+json2.min.js
 create mode 100644 static/scripts/tracker.js
 create mode 100644 static/stimuli/cricket.md
 create mode 100644 static/stimuli/ghosts.md
 create mode 100644 static/stimuli/moochi.md
 create mode 100644 static/stimuli/outwit.md
 create mode 100644 static/stimuli/raid.md
 create mode 100644 static/stimuli/species.md
 create mode 100644 static/stimuli/tennis.md
 create mode 100644 static/stimuli/vagabond.md
 create mode 100644 templates/ad.html
 create mode 100644 templates/base/ad.html
 create mode 100644 templates/base/consent.html
 create mode 100644 templates/base/layout.html
 create mode 100644 templates/base/questionnaire.html
 create mode 100644 templates/complete.html
 create mode 100644 templates/consent.html
 create mode 100644 templates/error-complete.html
 create mode 100644 templates/error.html
 create mode 100644 templates/exp.html
 create mode 100644 templates/instructions/instruct-ready.html
 create mode 100644 templates/launch.html
 create mode 100644 templates/layout.html
 create mode 100644 templates/questionnaire.html
 create mode 100644 templates/thanks.html
 create mode 100644 templates/waiting.html
GitClient: "git init"GitClient: "git add --all"GitClient: "git commit -m ""Experiment b46ab9b3-04ee-77a1-0a9c-8b971fe371ad"""
❯❯ Initializing app on Heroku...
Creating ⬢ dlgr-b46ab9b3... done
Setting buildpack to heroku/python... done
https://dlgr-b46ab9b3.herokuapp.com/ | https://git.heroku.com/dlgr-b46ab9b3.git
Setting CREATOR, DALLINGER_UID, HOST and restarting ⬢ dlgr-b46ab9b3... done, v3
CREATOR:       witekdev@protonmail.com
DALLINGER_UID: b46ab9b3-04ee-77a1-0a9c-8b971fe371ad
HOST:          https://dlgr-b46ab9b3.herokuapp.com
Buildpack added. Next release on dlgr-b46ab9b3 will use:
  1. heroku/python
  2. https://github.com/stomita/heroku-buildpack-phantomjs
Run git push heroku master to create a new release using these buildpacks.
Creating heroku-postgresql:hobby-dev on ⬢ dlgr-b46ab9b3... free
Database has been created and is available
 ! This database is empty. If upgrading, you can transfer
 ! data from another database with pg:copy
Created postgresql-opaque-62455 as DATABASE_URL
Use heroku addons:docs heroku-postgresql to view documentation
Creating heroku-redis:premium-0 on ⬢ dlgr-b46ab9b3... $15/month
Your add-on should be available in a few minutes.
redis-pointy-46468 is being created in the background. The app will restart when complete...
Use heroku addons:info redis-pointy-46468 to check creation progress
Use heroku addons:docs heroku-redis to view documentation
Creating papertrail on ⬢ dlgr-b46ab9b3... free
Welcome to Papertrail. Questions and ideas are welcome (support@papertrailapp.com). Happy logging!
Created papertrail-spherical-96593 as PAPERTRAIL_API_TOKEN
Use heroku addons:docs papertrail to view documentation
Setting auto_recruit, aws_access_key_id, aws_region, aws_secret_access_key, smtp_password, smtp_username, whimsical and restarting dlgr-b46ab9b3... done, v8

❯❯ Waiting for Redis...
Traceback (most recent call last):
  File "/home/witek/.virtualenvs/dlgr_env/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/witek/Dallinger/dallinger/command_line.py", line 290, in wrapper
    return f(**kwargs)
  File "/home/witek/Dallinger/dallinger/command_line.py", line 126, in wrapper
    result = func(*args, **kwargs)
  File "/home/witek/Dallinger/dallinger/command_line.py", line 392, in sandbox
    _deploy_in_mode('sandbox', app=app, verbose=verbose, log=log)
  File "/home/witek/Dallinger/dallinger/deployment.py", line 378, in _deploy_in_mode
    deploy_sandbox_shared_setup(log, verbose=verbose, app=app)
  File "/home/witek/Dallinger/dallinger/deployment.py", line 313, in deploy_sandbox_shared_setup
    r = redis.from_url(heroku_app.redis_url)
  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/redis/utils.py", line 19, in from_url
    return Redis.from_url(url, db, **kwargs)
  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/redis/client.py", line 602, in from_url
    connection_pool = ConnectionPool.from_url(url, db=db, **kwargs)
  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/redis/connection.py", line 920, in from_url
    'schemes (%s)' % valid_schemes)
ValueError: Redis URL must specify one of the followingschemes (redis://, rediss://, unix://)
(dlgr_env) witek@ubuntu:~/Dallinger/demos/dlgr/demos/bartlett1932$
```

**Comment by witekdev** [comment]
This bug seems to be some sort of timing issue perhaps?

As soon as I inject any sort of print/debug statements into the code, the "❯❯ Waiting for Redis..." step passes and the experiment continues to launch via "❯❯ Saving the URL of the postgres database..." and etc... 

Without such debug statements, I continue to get the ```ValueError: Redis URL must specify one of the followingschemes (redis://, rediss://, unix://) ``` above.

The url we receive from Heroku seems to be of the correct format:
(Pdb) heroku_app.redis_url
u'redis://h:[p8bcb81a19aaad5c46b296db55a3f75aa1af075845fc5c2f20d1345af0372efa3@ec2-35-153-174-124.compute-1.amazonaws.com](mailto:p8bcb81a19aaad5c46b296db55a3f75aa1af075845fc5c2f20d1345af0372efa3@ec2-35-153-174-124.compute-1.amazonaws.com):27429\n'

Revelant code bits that I have been inspecting:
"/home/witek/Dallinger/dallinger/deployment.py"
```
    # Wait for Redis database to be ready.
    log("Waiting for Redis...")
    ready = False
    while not ready:
        r = redis.from_url(heroku_app.redis_url)
        try:
            r.set("foo", "bar")
            ready = True
        except redis.exceptions.ConnectionError:
            time.sleep(2)
```
or in  File "/home/witek/.virtualenvs/dlgr_env/lib/python2.7/site-packages/redis/connection.py
```
    @classmethod
    def from_url(cls, url, db=None, decode_components=False, **kwargs):
        """
        Return a connection pool configured from the given URL.

        For example::

            redis://[:password]@localhost:6379/0
            rediss://[:password]@localhost:6379/0
            unix://[:password]@/path/to/socket.sock?db=0

        Three URL schemes are supported:

        - ```redis://``
          <https://www.iana.org/assignments/uri-schemes/prov/redis>`_ creates a
          normal TCP socket connection
        - ```rediss://``
          <https://www.iana.org/assignments/uri-schemes/prov/rediss>`_ creates
          a SSL wrapped TCP socket connection
        - ``unix://`` creates a Unix Domain Socket connection

        There are several ways to specify a database number. The parse function
        will return the first specified option:
            1. A ``db`` querystring option, e.g. redis://localhost?db=0
            2. If using the redis:// scheme, the path argument of the url, e.g.
               redis://localhost/0
            3. The ``db`` argument to this function.

        If none of these options are specified, db=0 is used.

        The ``decode_components`` argument allows this function to work with
        percent-encoded URLs. If this argument is set to ``True`` all ``%xx``
        escapes will be replaced by their single-character equivalents after
        the URL has been parsed. This only applies to the ``hostname``,
        ``path``, and ``password`` components.

        Any additional querystring arguments and keyword arguments will be
        passed along to the ConnectionPool class's initializer. The querystring
        arguments ``socket_connect_timeout`` and ``socket_timeout`` if supplied
        are parsed as float values. The arguments ``socket_keepalive`` and
        ``retry_on_timeout`` are parsed to boolean values that accept
        True/False, Yes/No values to indicate state. Invalid types cause a
        ``UserWarning`` to be raised. In the case of conflicting arguments,
        querystring arguments always win.

        """
        url = urlparse(url)
        url_options = {}

        for name, value in iteritems(parse_qs(url.query)):
            if value and len(value) > 0:
                parser = URL_QUERY_ARGUMENT_PARSERS.get(name)
                if parser:
                    try:
                        url_options[name] = parser(value[0])
                    except (TypeError, ValueError):
                        warnings.warn(UserWarning(
                            "Invalid value for `%s` in connection URL." % name
                        ))
                else:
                    url_options[name] = value[0]

        if decode_components:
            password = unquote(url.password) if url.password else None
            path = unquote(url.path) if url.path else None
            hostname = unquote(url.hostname) if url.hostname else None
        else:
            password = url.password
            path = url.path
            hostname = url.hostname

        # We only support redis://, rediss:// and unix:// schemes.
        if url.scheme == 'unix':
            url_options.update({
                'password': password,
                'path': path,
                'connection_class': UnixDomainSocketConnection,
            })

        elif url.scheme in ('redis', 'rediss'):
            url_options.update({
                'host': hostname,
                'port': int(url.port or 6379),
                'password': password,
            })

            # If there's a path argument, use it as the db argument if a
            # querystring value wasn't specified
            if 'db' not in url_options and path:
                try:
                    url_options['db'] = int(path.replace('/', ''))
                except (AttributeError, ValueError):
                    pass

            if url.scheme == 'rediss':
                url_options['connection_class'] = SSLConnection
        else:
            valid_schemes = ', '.join(('redis://', 'rediss://', 'unix://'))
            raise ValueError('Redis URL must specify one of the following'
                             'schemes (%s)' % valid_schemes)
```

**Comment by jessesnyder** [comment]
I bet when `heroku_app.redis_url` was `None` previously, the result when calling `redis.from_url()` was the connection error we were trapping in the exception handler. Now we're getting the `ValueError` in the same situation.
