### ISSUE TITLE
Error running "Running Experiments Programmatically" code

### ISSUE THREAD

**Issue by witekdev** [Dallinger/Dallinger#1677]
The syntax in http://docs.dallinger.io/en/latest/python_module.html has been found to be incorrect. While this has been addressed in https://github.com/Dallinger/Dallinger/pull/1676 there exists another issue, namely:

```
import dallinger

experiment = dallinger.experiments.Bartlett1932()
data = experiment.run(
    mode='live',
    base_payment=1.00,
)
```
gives:
```
Traceback (most recent call last):
  File "runrun.py", line 6, in <module>
    base_payment=1.00,
  File "/home/witek/Dallinger/dallinger/experiment.py", line 61, in new_meth
    return meth(self, *args, **kwargs)
  File "/home/witek/Dallinger/dallinger/experiment.py", line 507, in run
    exp_config=self.exp_config
  File "/home/witek/Dallinger/dallinger/deployment.py", line 253, in deploy_sandbox_shared_setup
    (id, tmp) = setup_experiment(log, debug=False, app=app, exp_config=exp_config)
  File "/home/witek/Dallinger/dallinger/deployment.py", line 125, in setup_experiment
    config.extend(exp_config)
  File "/home/witek/Dallinger/dallinger/config.py", line 132, in extend
    expected_type=expected_type,
TypeError: Got 'live' for mode, expected <type 'unicode'>
(dlgr_env) witek@ubuntu:~/Dallinger/demos/dlgr/demos/bartlett1932$
```

whereas using "debug":
```
import dallinger

experiment = dallinger.experiments.Bartlett1932()
data = experiment.run(
    mode='debug',
    base_payment=1.00,
)
```
works fine.

**Comment by witekdev** [comment]
I cannot reproduce this anymore with v5.0.6. 
A live Bartlett experiment starts up fine.
Closing..
