### ISSUE TITLE
Problem installing MarkupSafe

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#2054]
### Error on Travis builds:

```
Collecting markupsafe==1.0

  Using cached MarkupSafe-1.0.tar.gz (14 kB)

    ERROR: Command errored out with exit status 1:

     command: /home/travis/build/Dallinger/Dallinger/.tox/py36/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-acdxyot9/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-acdxyot9/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-acdxyot9/markupsafe/pip-egg-info

         cwd: /tmp/pip-install-acdxyot9/markupsafe/

    Complete output (5 lines):

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-install-acdxyot9/markupsafe/setup.py", line 6, in <module>

        from setuptools import setup, Extension, Feature

    ImportError: cannot import name 'Feature'

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

ERROR: InvocationError for command '/home/travis/build/Dallinger/Dallinger/.tox/py36/bin/pip install -r build-requirements.txt' (exited with code 1)
```

**Comment by jessesnyder** [comment]
Fixed; closing.
