### ISSUE TITLE
Dashboard monitor return "Internal server Error" when selecting specific network roles: 2pt

### ISSUE THREAD

**Issue by jacobyn** [Dallinger/Dallinger#2252]
When selecting "Network roles":

![image](https://user-images.githubusercontent.com/10518584/87873421-dd7c3f80-c9c1-11ea-94fc-40605c5bc076.png)

Here:

![image](https://user-images.githubusercontent.com/10518584/87873410-d1907d80-c9c1-11ea-99bf-c6a6b59ffa5d.png)

It leads to:
`Internal Server Error`

This is the error:

```
work_ids=4&network_ids=5&network_ids=6 HTTP/1.1" 401 186 0.000693
1:15:28 PM web.2    |  Traceback (most recent call last):
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask_sockets.py", line 40, in __call__
1:15:28 PM web.2    |      handler, values = adapter.match()
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/werkzeug/routing.py", line 1945, in match
1:15:28 PM web.2    |      raise NotFound()
1:15:28 PM web.2    |  werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
1:15:28 PM web.2    |  During handling of the above exception, another exception occurred:
1:15:28 PM web.2    |  Traceback (most recent call last):
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
1:15:28 PM web.2    |      self.run_application()
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/geventwebsocket/handler.py", line 87, in run_application
1:15:28 PM web.2    |      return super(WebSocketHandler, self).run_application()
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/gevent/pywsgi.py", line 923, in run_application
1:15:28 PM web.2    |      self.result = self.application(self.environ, self.start_response)
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
1:15:28 PM web.2    |      return self.wsgi_app(environ, start_response)
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask_sockets.py", line 48, in __call__
1:15:28 PM web.2    |      return self.wsgi_app(environ, start_response)
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
1:15:28 PM web.2    |      response = self.handle_exception(e)
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
1:15:28 PM web.2    |      reraise(exc_type, exc_value, tb)
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
1:15:28 PM web.2    |      raise value
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
1:15:28 PM web.2    |      response = self.full_dispatch_request()
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
1:15:28 PM web.2    |      rv = self.handle_user_exception(e)
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
1:15:28 PM web.2    |      reraise(exc_type, exc_value, tb)
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
1:15:28 PM web.2    |      raise value
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
1:15:28 PM web.2    |      rv = self.dispatch_request()
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
1:15:28 PM web.2    |      return self.view_functions[rule.endpoint](**req.view_args)
1:15:28 PM web.2    |    File "/Users/jacoby/.virtualenvs/d6/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
1:15:28 PM web.2    |      return func(*args, **kwargs)
1:15:28 PM web.2    |    File "/Users/jacoby/Dallinger/dallinger/experiment_server/dashboard.py", line 560, in monitoring
1:15:28 PM web.2    |      network_structure = exp.network_structure(**request.args.to_dict(flat=False))
1:15:28 PM web.2    |  TypeError: network_structure() got an unexpected keyword argument 'network_roles'
1:15:28 PM web.2    |  2020-07-19T11:15:28Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '55482', 'HTTP_HOST': '0.0.0.0:5001', (hidden keys: 27)} failed with TypeError
1:15:28 PM web.2    |  INFO:geventwebsocket.handler:127.0.0.1 - - [2020-07-19 13:15:28] "GET /dashboard/monitoring?network_roles=experiment&network_ids=1&network_ids=2&network_ids=3&network_ids=4&network_ids=5&network_ids=6 HTTP/1.1" 500 161 0.064436
```

**Comment by alecpm** [comment]
Does the experiment class you are using here have a custom `network_structure` class? The method on the default `Experiment` class takes arbitrary `**kwargs` and should not ever throw this exception. I think the `psynet.experiment.Experiment.network_structure` method will need to either be removed (so the base class version is used), or accept `**kw` and perform filtering.

**Comment by alecpm** [comment]
I guess alternatively we could rename the method so it doesn't collide with the existing `psynet.Experiment` method. Since they are intended to serve the same purpose, that seems a little odd.

**Comment by pmcharrison** [comment]
> Does the experiment class you are using here have a custom network_structure class?

Thanks, @alecpm - that was the issue indeed! No changes needed, then.
