### ISSUE TITLE
Can't hibernate an experiment 

### ISSUE THREAD

**Issue by stefanuddenberg** [Dallinger/Dallinger#2412]
Calling `dallinger hibernate` leads to the following error on Dallinger 6.5.0:

```
❯❯ The database backup URL is...
Traceback (most recent call last):
  File "/home/stefanu/anaconda3/envs/dallinger/bin/dallinger", line 8, in <module>
    sys.exit(dallinger())
  File "/home/stefanu/anaconda3/envs/dallinger/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/stefanu/anaconda3/envs/dallinger/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/stefanu/anaconda3/envs/dallinger/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stefanu/anaconda3/envs/dallinger/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stefanu/anaconda3/envs/dallinger/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/stefanu/anaconda3/envs/dallinger/lib/python3.7/site-packages/dallinger/command_line.py", line 700, in hibernate
    backup_url = data.backup(app)
  File "/home/stefanu/anaconda3/envs/dallinger/lib/python3.7/site-packages/dallinger/data.py", line 133, in backup
    bucket.upload_file(filename, key)
AttributeError: 'NoneType' object has no attribute 'upload_file'
```

**Comment by stefanuddenberg** [comment]
Figured it out: needed AmazonS3FullAccess on my `dallinger` AWS IAM user.
