### ISSUE TITLE
paramiko docker dependency raising error on Heroku

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#2579]
## Current Behavior
```
heroku[web.1]: Starting process with command `dallinger_heroku_web`
app[web.1]: Traceback (most recent call last):
app[web.1]: File "/app/.heroku/python/bin/dallinger_heroku_web", line 6, in <module>
app[web.1]: from pkg_resources import load_entry_point
app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3262, in <module>
app[web.1]: def _initialize_master_working_set():
app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3245, in _call_aside
app[web.1]: f(*args, **kwargs)
app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3274, in _initialize_master_working_set
app[web.1]: working_set = WorkingSet._build_master()
app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 584, in _build_master
app[web.1]: ws.require(__requires__)
app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 901, in require
app[web.1]: needed = self.resolve(parse_requirements(requirements))
app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/pkg_resources/__init__.py", line 787, in resolve
app[web.1]: raise DistributionNotFound(req, requirers)
app[web.1]: pkg_resources.DistributionNotFound: The 'paramiko>=2.4.2; extra == "ssh"' distribution was not found and is required by docker
heroku[web.1]: Process exited with status 1
heroku[web.1]: State changed from starting to crashed
```

## Steps to Reproduce (for bugs)
Deploy Bartlett1932 demo to heroku using the Dallinger `master` branch

## Your Environment
* Dallinger version used: `master`

**Comment by alecpm** [comment]
I added a branch `issues/2579-paramiko-dep` that pins some of these newly introduced dependencies in `constraints.txt` and `constraints-deps.txt`, but still get the same error. I think it's probably best if @silviot takes a look at this. I do think we should consider making docker and related requirements part of an extra in setup.py, as we do for the `data` extra so that we don't force installation of docker, etc. on normal Heroku deploys.
