### ISSUE TITLE
SQLAlchemy error

### ISSUE THREAD

**Issue by polvanrijn** [Dallinger/Dallinger#2599]
A SQLAlchemy error occurs, that does not occur in the branch `v7.0.0`.

```
11:55:59 AM web.1   |  INFO:root:Received a response from participant 1 on page aeb74d93-828c-61d5-09e0-b82844ecea04.
11:55:59 AM web.1   |  INFO:root:Preparing trial for participant 1.
11:55:59 AM web.1   |  INFO:root:Found 3 network(s) for participant 1.
11:55:59 AM web.1   |  Traceback (most recent call last):
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask_sockets.py", line 40, in __call__
11:55:59 AM web.1   |      handler, values = adapter.match()
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/werkzeug/routing.py", line 1945, in match
11:55:59 AM web.1   |      raise NotFound()
11:55:59 AM web.1   |  werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
11:55:59 AM web.1   |  During handling of the above exception, another exception occurred:
11:55:59 AM web.1   |  Traceback (most recent call last):
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
11:55:59 AM web.1   |      self.dialect.do_execute(
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
11:55:59 AM web.1   |      cursor.execute(statement, parameters)
11:55:59 AM web.1   |  psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "{"vector": [-186.09645266230518, 27.33110223817971, -249.63502017141434, 651.5123252314334, -22.23213508343133], "active_index": 4}"
11:55:59 AM web.1   |  The above exception was the direct cause of the following exception:
11:55:59 AM web.1   |  Traceback (most recent call last):
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
11:55:59 AM web.1   |      self.run_application()
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/geventwebsocket/handler.py", line 87, in run_application
11:55:59 AM web.1   |      return super(WebSocketHandler, self).run_application()
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/gevent/pywsgi.py", line 945, in run_application
11:55:59 AM web.1   |      self.result = self.application(self.environ, self.start_response)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
11:55:59 AM web.1   |      return self.wsgi_app(environ, start_response)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask_sockets.py", line 48, in __call__
11:55:59 AM web.1   |      return self.wsgi_app(environ, start_response)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
11:55:59 AM web.1   |      response = self.handle_exception(e)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
11:55:59 AM web.1   |      reraise(exc_type, exc_value, tb)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
11:55:59 AM web.1   |      raise value
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
11:55:59 AM web.1   |      response = self.full_dispatch_request()
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
11:55:59 AM web.1   |      rv = self.handle_user_exception(e)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
11:55:59 AM web.1   |      reraise(exc_type, exc_value, tb)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
11:55:59 AM web.1   |      raise value
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
11:55:59 AM web.1   |      rv = self.dispatch_request()
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
11:55:59 AM web.1   |      return self.view_functions[rule.endpoint](**req.view_args)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/experiment.py", line 674, in route_response
11:55:59 AM web.1   |      res = exp.process_response(
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/experiment.py", line 431, in process_response
11:55:59 AM web.1   |      self.timeline.advance_page(self, participant)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/timeline.py", line 1009, in advance_page
11:55:59 AM web.1   |      new_event.consume(experiment, participant)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/timeline.py", line 84, in consume
11:55:59 AM web.1   |      call_function(
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/utils.py", line 105, in call_function
11:55:59 AM web.1   |      return function(*arg_values)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/trial/main.py", line 1229, in _prepare_trial
11:55:59 AM web.1   |      trial = self.prepare_trial(experiment=experiment, participant=participant)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/trial/main.py", line 1617, in prepare_trial
11:55:59 AM web.1   |      self._grow_network(network, participant, experiment)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/trial/main.py", line 1712, in _grow_network
11:55:59 AM web.1   |      grown = self.grow_network(network, participant, experiment)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/trial/chain.py", line 1345, in grow_network
11:55:59 AM web.1   |      head = network.head
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/trial/chain.py", line 297, in head
11:55:59 AM web.1   |      return self.get_node_with_degree(degree)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/psynet/psynet/trial/chain.py", line 304, in get_node_with_degree
11:55:59 AM web.1   |      ChainNode.query.filter_by(degree=degree, network_id=self.id, failed=False)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3373, in all
11:55:59 AM web.1   |      return list(self)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
11:55:59 AM web.1   |      return self._execute_and_instances(context)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
11:55:59 AM web.1   |      result = conn.execute(querycontext.statement, self._params)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
11:55:59 AM web.1   |      return meth(self, multiparams, params)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
11:55:59 AM web.1   |      return connection._execute_clauseelement(self, multiparams, params)
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
11:55:59 AM web.1   |      ret = self._execute_context(
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
11:55:59 AM web.1   |      self._handle_dbapi_exception(
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
11:55:59 AM web.1   |      util.raise_(
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
11:55:59 AM web.1   |      raise exception
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
11:55:59 AM web.1   |      self.dialect.do_execute(
11:55:59 AM web.1   |    File "/Users/pol.van-rijn/.virtualenvs/psynet/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
11:55:59 AM web.1   |      cursor.execute(statement, parameters)
11:55:59 AM web.1   |  sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type integer: "{"vector": [-186.09645266230518, 27.33110223817971, -249.63502017141434, 651.5123252314334, -22.23213508343133], "active_index": 4}"
11:55:59 AM web.1   |  [SQL: SELECT node.id AS node_id, node.creation_time AS node_creation_time, node.property1 AS node_property1, node.property2 AS node_property2, node.property3 AS node_property3, node.property4 AS node_property4, node.property5 AS node_property5, node.failed AS node_failed, node.failed_reason AS node_failed_reason, node.time_of_death AS node_time_of_death, node.details AS node_details, node.type AS node_type, node.network_id AS node_network_id, node.participant_id AS node_participant_id 
11:55:59 AM web.1   |  FROM node 
11:55:59 AM web.1   |  WHERE CAST(node.property1 AS INTEGER) = %(param_1)s AND node.network_id = %(network_id_1)s AND node.failed = false AND node.type IN (%(type_1)s, %(type_2)s, %(type_3)s, %(type_4)s, %(type_5)s, %(type_6)s, %(type_7)s) ORDER BY node.id]
11:55:59 AM web.1   |  [parameters: {'param_1': 1, 'network_id_1': 4, 'type_1': 'chain_node', 'type_2': 'imitation_chain_node', 'type_3': 'gibbs_node', 'type_4': 'audio_imitation_chain_node', 'type_5': 'audio_gibbs_node', 'type_6': 'custom_node', 'type_7': 'custom_node'}]
11:55:59 AM web.1   |  (Background on this error at: http://sqlalche.me/e/13/9h9h
```

**Comment by pmcharrison** [comment]
@polvanrijn, I have patched the URL parameter problem in PsyNet [MR 133](https://gitlab.com/computational-audition-lab/psynet/-/merge_requests/133) and moved the relevant Dallinger problem to the issue #2604.

I cannot reproduce your SQLAlchemy error, even with the following code you mentioned the other day,

``` py
from psynet.prescreen import (
    AttentionCheck,
    HeadphoneCheck
)
```

so if you experience it again please do share a reproducible example.

**Comment by pmcharrison** [comment]
I have now debugged the error, and can confirm that it's not a Dallinger issue.
