### ISSUE TITLE
`dallinger generate-constraints` fails when a library is imported in experiment.py which is only to be installed from `requirements.txt` 

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#2831]
## Expected Behavior

TODO

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Dallinger version used:
* Operating System and version (desktop or mobile):
* Browser and version (e.g. Chrome 39, node.js 5.4):
* Link to your project:

**Comment by pmcharrison** [comment]
i.e., a dependency that you don't have installed locally, but you want to be installed on Heroku?

**Comment by silviot** [comment]
The contents of `experiment.py` should not come into play when invoking `dallinger generate-constraints`.
Can you provide an example of a library that causes the error, and the output of `dallinger generate-constraints`?

**Comment by fmhoeger** [comment]
Hi @silviot , after further investigating this it turned out that a dependency with a wrong version was installed. Therefore, when trying to install the psynet project located here:
[https://gitlab.com/computational-audition-lab/tapping-mvp/tapping-keith.git](https://gitlab.com/computational-audition-lab/tapping-mvp/tapping-keith.git)
`dallinger generate-constraints` resulted in the following error:
```
(psynet) frank@franks ~/projects/tapping-keith (master)$ dallinger generate-constraints
Traceback (most recent call last):
  File "/home/frank/.virtualenvs/psynet/bin/dallinger", line 33, in <module>
    sys.exit(load_entry_point('dallinger', 'console_scripts', 'dallinger')())
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frank/.virtualenvs/psynet/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frank/projects/Dallinger/dallinger/command_line/utils.py", line 68, in wrapper
    if not verify_package(kwargs.get("verbose")):
  File "/home/frank/projects/Dallinger/dallinger/command_line/utils.py", line 83, in verify_package
    verify_experiment_module(verbose),
  File "/home/frank/projects/Dallinger/dallinger/command_line/utils.py", line 146, in verify_experiment_module
    from dallinger_experiment import experiment
  File "/tmp/tmpc5kf_s8v/TEMP_VERIFICATION_PACKAGE/experiment.py", line 36, in <module>
    from repp.config import sms_tapping
ImportError: cannot import name 'sms_tapping' from 'repp.config' (/home/frank/.virtualenvs/psynet/src/repp/repp/config.py) 
```
This was happening at the time I was first reporting the issue, still being unaware of the wrong version of the installed `repp` library. It seems the contents of `experiment.py` do come into play when invoking `dallinger generate-constraints` but we can fix it by installing the correct version of the dependency (`repp` in this case). Does that make sense and we can just close the issue?

**Comment by pmcharrison** [comment]
Hi Frank, do you get the same issue if you just run dallinger verify?

**Comment by silviot** [comment]
RIght! The contents of `experiment.py` _do_ come into play, since the experiment is verified before doing the constraints generation. For the verification to work `experiment.py` must be importable locally.
