### ISSUE TITLE
The `dallinger awaken` command throws an error

### ISSUE THREAD

**Issue by Luke-Poeppel** [Dallinger/Dallinger#3091]
The `dallinger awaken --app APP_ID` command throws an s3-related error. 

## Expected Behavior

After running `dallinger hibernate --app APP_ID` command, one should be able to run`dallinger awaken --app APP_ID` to re-add the scaled-down dynos. 

## Current Behavior

Running `dallinger awaken --app APP_ID` on a hibernating app throws an s3-related error:
```
(env) lukepoeppel@Spock kronos_i % dallinger awaken --app kr1hibtest
/Users/lukepoeppel/CAP/Experiments/kronos_i/env/src/psynet/psynet/page.py:439: DeprecationWarning: psynet.page.TextInputPage is deprecated. Use :class:`psynet.modular_page.ModularPage` in combination with :class:`psynet.modular_page.Prompt` and :class:`psynet.modular_page.TextControl` instead.
  warnings.warn(
/Users/lukepoeppel/CAP/Experiments/kronos_i/env/src/psynet/psynet/page.py:439: DeprecationWarning: psynet.page.TextInputPage is deprecated. Use :class:`psynet.modular_page.ModularPage` in combination with :class:`psynet.modular_page.Prompt` and :class:`psynet.modular_page.TextControl` instead.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/lukepoeppel/CAP/Experiments/kronos_i/env/bin/dallinger", line 8, in <module>
    sys.exit(dallinger())
  File "/Users/lukepoeppel/CAP/Experiments/kronos_i/env/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/lukepoeppel/CAP/Experiments/kronos_i/env/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/lukepoeppel/CAP/Experiments/kronos_i/env/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/lukepoeppel/CAP/Experiments/kronos_i/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/lukepoeppel/CAP/Experiments/kronos_i/env/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lukepoeppel/CAP/Experiments/kronos_i/env/lib/python3.9/site-packages/dallinger/command_line/__init__.py", line 686, in awaken
    key = bucket.lookup("{}.dump".format(id))
AttributeError: 's3.Bucket' object has no attribute 'lookup'
```

## Steps to Reproduce (for bugs)

I haven't tested, but I would guess the same issue would appear when sandboxing one of the demos.

**Comment by jessesnyder** [comment]
Looks like we missed an API change in the upgrade to boto3 several years ago. I think this is relevant:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/migrations3.html#accessing-a-bucket
