### ISSUE TITLE
RequestError when calling UpdateExpirationForHIT

### ISSUE THREAD

**Issue by fotinidelig** [Dallinger/Dallinger#3109]
While running an app something triggered a RequestError with the following output:

```
dallinger.mturk.MTurkServiceException: Failed to extend time until expiration of HIT: 2021-07-14 20:26:06+00:00
An error occurred (RequestError) when calling the UpdateExpirationForHIT operation: The idempotency token "3VJ4PFXFJ5VXUC3I783DUQKOMF2UAWWed Jul 14 20:26:06 UTC 2021" has already been processed. (1626172412406)

```
## Current Behavior
This was triggered without any attempt of expiring the HIT (or extending it), maybe it points out some other internal error not seen here?

**Comment by pmcharrison** [comment]
Can you share the full stack trace too?
________________________________
From: fotinidelig ***@***.***>
Sent: 13 July 2021 14:14
To: Dallinger/Dallinger ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Dallinger/Dallinger] RequestError when calling UpdateExpirationForHIT (#3109)


While running an app something triggered a RequestError with the following output:

dallinger.mturk.MTurkServiceException: Failed to extend time until expiration of HIT: 2021-07-14 20:26:06+00:00
An error occurred (RequestError) when calling the UpdateExpirationForHIT operation: The idempotency token "3VJ4PFXFJ5VXUC3I783DUQKOMF2UAWWed Jul 14 20:26:06 UTC 2021" has already been processed. (1626172412406)



Current Behavior

This was triggered without any attempt of expiring the HIT (or extending it), maybe it points out some other internal error not seen here?

**Comment by fotinidelig** [comment]
Oh yes sure!

```
 Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1 2021-07-13 10:33:32,410 Failed to extend time until expiration of HIT: 2021-07-14 20:26:06+00:00
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1 An error occurred (RequestError) when calling the UpdateExpirationForHIT operation: The idempotency token "3VJ4PFXFJ5VXUC3I783DUQKOMF2UAWWed Jul 14 20:26:06 UTC 2021" has already been processed. (1626172412406)
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1 Traceback (most recent call last):
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1   File "/app/.heroku/python/lib/python3.9/site-packages/dallinger/mturk.py", line 549, in update_expiration_for_hit
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1     response = self.mturk.update_expiration_for_hit(
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1   File "/app/.heroku/python/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1     return self._make_api_call(operation_name, kwargs)
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1   File "/app/.heroku/python/lib/python3.9/site-packages/botocore/client.py", line 705, in _make_api_call
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1     raise error_class(parsed_response, operation_name)
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1 botocore.errorfactory.RequestError: An error occurred (RequestError) when calling the UpdateExpirationForHIT operation: The idempotency token "3VJ4PFXFJ5VXUC3I783DUQKOMF2UAWWed Jul 14 20:26:06 UTC 2021" has already been processed. (1626172412406)
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1 During handling of the above exception, another exception occurred:
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1 Traceback (most recent call last):
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1   File "/app/.heroku/python/lib/python3.9/site-packages/dallinger/recruiters.py", line 709, in recruit
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1     return self.mturkservice.extend_hit(
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1   File "/app/.heroku/python/lib/python3.9/site-packages/dallinger/mturk.py", line 528, in extend_hit
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1     self.update_expiration_for_hit(hit_id, duration_hours)
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1   File "/app/.heroku/python/lib/python3.9/site-packages/dallinger/mturk.py", line 553, in update_expiration_for_hit
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1     raise MTurkServiceException(
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1 dallinger.mturk.MTurkServiceException: Failed to extend time until expiration of HIT: 2021-07-14 20:26:06+00:00
Jul 13 03:33:32 dlgr-rating-pleasant-1d app/worker.1 An error occurred (RequestError) when calling the UpdateExpirationForHIT operation: The idempotency token "3VJ4PFXFJ5VXUC3I783DUQKOMF2UAWWed Jul 14 20:26:06 UTC 2021" has already been processed. (1626172412406)
```
