### ISSUE TITLE
Missing required values when creating Participant

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#3153]
## Current Behavior
From experiment log provided by Emanuel Tort:
```
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
     response = self.full_dispatch_request()
   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/app/.heroku/python/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
     raise value
   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
     rv = self.dispatch_request()
   File "/app/.heroku/python/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/app/.heroku/python/lib/python3.7/site-packages/dallinger/experiment_server/experiment_server.py", line 853, in post_participant
     return create_participant(mode=mode, **participant_info)
   File "/app/.heroku/python/lib/python3.7/site-packages/dallinger/db.py", line 160, in wrapper
     result = func(*args, **kw)
   File "/app/.heroku/python/lib/python3.7/site-packages/dallinger/experiment_server/experiment_server.py", line 821, in create_participant
     entry_information,
   File "/app/.heroku/python/lib/python3.7/site-packages/dallinger/experiment.py", line 433, in create_participant
     entry_information=entry_information,
   File "<string>", line 4, in __init__
   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 480, in _initialize_instance
     manager.dispatch.init_failure(self, args, kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
     with_traceback=exc_tb,
   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
     raise exception
   File "/app/.heroku/python/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 477, in _initialize_instance
     return manager.original_init(*mixed[1:], **kwargs)
   File "/app/.heroku/python/lib/python3.7/site-packages/dallinger/models.py", line 280, in __init__
     self.unique_id = worker_id + ":" + assignment_id
 TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I think Dallinger-generated emailed error reports are a secondary symptom of the same problem, since they show an assignment ID of "unknown":

```
Dear experimenter,

This is an automated email from Dallinger. You are receiving this email because
a recruited participant has been unable to complete the experiment due to
a bug.

The application id is: 476fedb5-9ed7-d7a4-4098-aca8bff55a2c

The information about the failed HIT is recorded in the database in the
Notification table, with assignment_id unknown.

To see the logs, use the command "dallinger logs --app 476fedb5-9ed7-d7a4-4098-aca8bff55a2c"
To pause the app, use the command "dallinger hibernate --app 476fedb5-9ed7-d7a4-4098-aca8bff55a2c"
To destroy the app, use the command "dallinger destroy --app 476fedb5-9ed7-d7a4-4098-aca8bff55a2c"
The Dallinger dev. team.
```
## Steps to Reproduce (for bugs)
Unknown

## Context
Live experiment, heroku ID `ising-int1-3aggr`

## Your Environment

* Dallinger version used: 7.5.0

**Comment by jessesnyder** [comment]
@pmcharrison I think this error is due to `assignement_id` having a value of `None` after passing through the `/participant` route and the experiment's `normalize_entry_information()` method. Any chance something is going wrong here that's specific to the experiment?

**Comment by pmcharrison** [comment]
Strange - we are not touching `normalize_entry_information` in our current experiments. Do you think this could come from a client passing the wrong URL (e.g. copy-paste error)?

**Comment by jessesnyder** [comment]
Are you also surprised it's using the newer `/participant` route instead of the "classic" one that's called with a list of URL params? If so, I think it might be a URL copy paste error. The first thing the JS `createParticipant()` function does is check for the existence of an assignment ID in order to determine which version of the route to call. If there's no assignment ID (it wasn't present in the URL), then it uses the newer version of the `/participant` route, and all values for assignment ID, worker ID, etc. are expected to be extractable from the post data. This is ultimately where things are failing, because there's no `assignment_id` key in the post data.

**Comment by pmcharrison** [comment]
Yes - I don't see any code of ours calling upon that route, so your explanation is probably right, then? What do you reckon, would you like to file an issue proposal concerning better error reporting for this case? I don't think it's urgent but it would be nice to have in the coming months.

**Comment by jessesnyder** [comment]
I agree that would be helpful. We could wrap the call [here](https://github.com/Dallinger/Dallinger/blob/master/dallinger/experiment_server/experiment_server.py#L814) in a try/except, and log the exception along with the arguments passed to `create_participant()`.

**Comment by jessesnyder** [comment]
@pmcharrison I was unable to reproduce this in debug mode with the Bartlett demo without resorting to mutating the values in `dallinger.identity` with the browser dev tools. I'm mystified how this is happening, but that seemed like further reason to add the proposed logging/error handling, so that's in https://github.com/Dallinger/Dallinger/pull/3154

**Comment by pmcharrison** [comment]
Thank you very much, @jessesnyder. I have a suspicion I know what is happening here. Your logging will be helpful in sorting it for us!
