### ISSUE TITLE
Define demo dependency bump steps for release process

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#3184]
## Expected Behavior
When we release a new version to pypi, the demos should be using dependencies defined in that release, and should be pinned to that dallinger release.

Once process is defined, contributing_to_dallinger.rst should be updated to reflect the new steps.

## Dependent Issue
https://github.com/Dallinger/Dallinger/issues/3145 will be easier to solve once this issue is fixed, and should be considered in coming up with the solution for this issue.

## Current Behavior
Currently we try to re-generate constraints for demos by accessing the tag with the new version number on github, but the tag doesn't exist yet:
```
Compiling vox_populi
Compiling constraints.txt file from requirements.txt and https://raw.githubusercontent.com/Dallinger/Dallinger/v7.6.0/dev-requirements.txt
Traceback (most recent call last):
  File "/Users/jesses/.pyenv/versions/dallinger/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/piptools/scripts/compile.py", line 407, in cli
    constraints.extend(
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/piptools/_compat/pip_compat.py", line 23, in parse_requirements
    for parsed_req in _parse_requirements(
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 138, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 328, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 356, in _parse_and_recurse
    yield from self._parse_and_recurse(req_path, nested_constraint)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 332, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 362, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/pip/_internal/req/req_file.py", line 538, in get_file_content
    raise_for_status(resp)
  File "/Users/jesses/.pyenv/versions/3.9.2/envs/dallinger/lib/python3.9/site-packages/pip/_internal/network/utils.py", line 53, in raise_for_status
    raise NetworkConnectionError(http_error_msg, response=resp)
pip._internal.exceptions.NetworkConnectionError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/Dallinger/Dallinger/v7.6.0/dev-requirements.txt
```

See also problems in build of release PR:
https://github.com/Dallinger/Dallinger/runs/3234600095

## Steps to Reproduce (for bugs)

1. bump dallinger version for release (`bumpversion minor` or similar)
2. attempt to bump pins for demos: `scripts/update_experiments_constraints.sh`

**Comment by jessesnyder** [comment]
Fixed; closing
