### ISSUE TITLE
create_participant in dallinger.js failing?

### ISSUE THREAD

**Issue by thomasmorgan** [Dallinger/Dallinger#338]
I am getting the following error in the logs:

```
Dec 10 15:47:30 dlgr-2a06547a app/web.1:  2016-12-10 23:47:29,903 Exception on /node/undefined [POST] 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:  Traceback (most recent call last): 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      response = self.full_dispatch_request() 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      rv = self.handle_user_exception(e) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      reraise(exc_type, exc_value, tb) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      rv = self.dispatch_request() 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      return self.view_functions[rule.endpoint](**req.view_args) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/custom.py", line 549, in create_node 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      query.filter_by(id=participant_id).one() 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2754, in one 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      ret = self.one_or_none() 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2724, in one_or_none 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      ret = list(self) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2795, in __iter__ 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      return self._execute_and_instances(context) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2818, in _execute_and_instances 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      result = conn.execute(querycontext.statement, self._params) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      return meth(self, multiparams, params) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      return connection._execute_clauseelement(self, multiparams, params) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      compiled_sql, distilled_params 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      context) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      exc_info 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      reraise(type(exception), exception, tb=exc_tb, cause=cause) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      context) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 462, in do_execute 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:      cursor.execute(statement, parameters) 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:  DataError: (psycopg2.DataError) invalid input syntax for integer: "undefined" 
Dec 10 15:47:30 dlgr-2a06547a app/web.1:  LINE 3: WHERE participant.id = 'undefined'
```

What this means is that someone has managed to get to the experiment page without having a participant_id. Either the request to create a participant object (in the consent page) failed, was not even sent or the value was subsequently lost.

Perhaps the most likely option is that participants might be consenting before the request is complete and so they move onto the next page before they are assigned a participant_id. If so, the following change to the consent page will fix this:

```
$("#consent").click(function() {
        if (participant_id != "undefined") {
            allow_exit();
            go_to_page("instructions/instruct-1");
        }
    });
```
i.e. only advance if you have a participant_id

If this works a better fix would be for the create_participant method to lock the page until a participant_id is acquired. Maybe with some sort of splash saying "creating participant, please wait".

For background, here is where the create_participant method is called:

```
$(document).ready(function() {
    create_participant();
});
```

and here is the function in dallinger.js

```
create_participant = function() {

    // check if the local store is available, and if so, use it.
    if (typeof store != "undefined") {
        url = "/participant/" +
            store.get("worker_id") + "/" +
            store.get("hit_id") + "/" +
            store.get("assignment_id") + "/" +
            store.get("mode");
    } else {
        url = "/participant/" +
            worker_id + "/" +
            hit_id + "/" +
            assignment_id + "/" +
            mode;
    }

    if (participant_id === undefined || participant_id === "undefined") {
        reqwest({
            url: url,
            method: "post",
            type: "json",
            success: function(resp) {
                console.log(resp);
                participant_id = resp.participant.id;
            },
            error: function (err) {
                errorResponse = JSON.parse(err.response);
                $("body").html(errorResponse.html);
            }
        });
    }
};
```

**Comment by thomasmorgan** [comment]
Further tests suggest that this error is due to some participants advancing to the next page prior to the request to make a participant object completing.

For now I have my experiment's consent.js overwrite the create_participant method with the following:

```
// make a new participant
create_participant = function() {

    // check if the local store is available, and if so, use it.
    if (typeof store != "undefined") {
        url = "/participant/" +
            store.get("worker_id") + "/" +
            store.get("hit_id") + "/" +
            store.get("assignment_id") + "/" +
            store.get("mode");
    } else {
        url = "/participant/" +
            worker_id + "/" +
            hit_id + "/" +
            assignment_id + "/" +
            mode;
    }

    if (participant_id === undefined || participant_id === "undefined") {
        reqwest({
            url: url,
            method: "post",
            type: "json",
            success: function(resp) {
                console.log(resp);
                participant_id = resp.participant.id;
                $("#consent").show();
                $("#refresh-prompt").hide();
            },
            error: function (err) {
                errorResponse = JSON.parse(err.response);
                $("body").html(errorResponse.html);
            }
        });
    }
};
```
i.e. the consent button is hidden until the request completes
