### ISSUE TITLE
Regression in launching experiments from Python API

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#404]
PR #369 made it possible to run experiments in the following way:

```
import dallinger as dlgr
exp = dlgr.experiments.Bartlett1932()
exp.sandbox({"Server Parameters": {"dyno_type": "hobby"}})
```

However, this no longer works as expected.

## Expected Behavior
The experiment should be launched in sandbox mode.

## Current Behavior
```
Dallinger/demos/bartlett1932 git/development
❯ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dallinger
>>> exp = dallinger.experiments.Bartlett1932()
>>> exp.sandbox({"Server Parameters": {"dyno_type": "hobby"}})

        ____        ____
       / __ \____ _/ / (_)___  ____ ____  _____
      / / / / __ `/ / / / __ \/ __ `/ _ \/ ___/
     / /_/ / /_/ / / / / / / / /_/ /  __/ /
    /_____/\__,_/_/_/_/_/ /_/\__, /\___/_/
                            /____/

                    Laboratory automation for
           the behavioral and social sciences.


❯❯ Verifying that directory is compatible with Dallinger...
✓ config.txt is PRESENT
✓ experiment.py is PRESENT
✓ requirements.txt is PRESENT
/Users/jordansuchow/.virtualenvs/dallinger/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py:1034: SAWarning: Reassigning polymorphic association for identity 'war_of_the_ghosts_source' from <Mapper at 0x1090e9dd0; WarOfTheGhostsSource> to <Mapper at 0x10965c9d0; WarOfTheGhostsSource>: Check for duplicate use of 'war_of_the_ghosts_source' as value for polymorphic_identity.
  self, self.polymorphic_identity)
✓ experiment.py defines 1 experiment
✓ README is OK
✓ no file conflicts

❯❯ Experiment id is 63c3dd9f-4119-4d5e-9758-2d6980aef6c0
/var/folders/9l/s_hqlr1520s24xp9wz0g5k2m0000gn/T/tmpyVlgyH/63c3dd9f-4119-4d5e-9758-2d6980aef6c0

❯❯ Freezing the experiment package...

❯❯ Making sure that you are logged in to Heroku.
suchow@post.harvard.edu

Initialized empty Git repository in /private/var/folders/9l/s_hqlr1520s24xp9wz0g5k2m0000gn/T/tmpyVlgyH/63c3dd9f-4119-4d5e-9758-2d6980aef6c0/.git/
[master (root-commit) 373e1c5] Experiment 63c3dd9f-4119-4d5e-9758-2d6980aef6c0
 39 files changed, 1286 insertions(+)
 create mode 100644 -
 create mode 100644 Procfile
 create mode 100644 README.md
 create mode 100644 __init__.py
 create mode 100644 __init__.pyc
 create mode 100644 clock.py
 create mode 100644 config.txt
 create mode 100644 dallinger_experiment.py
 create mode 100644 experiment.pyc
 create mode 100644 experiment_id.txt
 create mode 100644 psiturkapp.py
 create mode 100644 requirements.txt
 create mode 100644 static/css/bootstrap.min.css
 create mode 100644 static/css/dallinger.css
 create mode 100644 static/favicon.ico
 create mode 100644 static/images/logo.png
 create mode 100644 static/robots.txt
 create mode 100644 static/scripts/dallinger.js
 create mode 100644 static/scripts/experiment.js
 create mode 100644 static/scripts/markdown.min.js
 create mode 100755 static/scripts/reqwest.min.js
 create mode 100644 static/scripts/store+json2.min.js
 create mode 100644 static/stimuli/cricket.md
 create mode 100644 static/stimuli/ghosts.md
 create mode 100644 static/stimuli/moochi.md
 create mode 100644 static/stimuli/outwit.md
 create mode 100644 static/stimuli/raid.md
 create mode 100644 static/stimuli/species.md
 create mode 100644 static/stimuli/tennis.md
 create mode 100644 static/stimuli/vagabond.md
 create mode 100644 templates/ad.html
 create mode 100644 templates/complete.html
 create mode 100644 templates/consent.html
 create mode 100644 templates/error.html
 create mode 100644 templates/exp.html
 create mode 100644 templates/instructions.html
 create mode 100644 templates/launch.html
 create mode 100644 templates/questionnaire.html
 create mode 100644 worker.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/experiment.py", line 38, in new_meth
    return meth(self, *args, **kwargs)
  File "/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/experiment.py", line 402, in sandbox
    exp_config=exp_config)
  File "/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/command_line.py", line 348, in deploy_sandbox_shared_setup
    config.load_config()
  File "/Users/jordansuchow/Dropbox/Berkeley/Projects/Current/Dallinger/dallinger/config.py", line 98, in load_config
    raise ValueError("Already loaded")
ValueError: Already loaded
```

## Steps to Reproduce (for bugs)
```
import dallinger as dlgr
exp = dlgr.experiments.Bartlett1932()
exp.sandbox({"Server Parameters": {"dyno_type": "hobby"}})
```

## Your Environment
Tested on the `development` branch at a996b6602913dd656ec8be3d990fff03cd01aae6.

**Comment by alecpm** [comment]
Now the PR #389 is merged this is working, but it's now using the new flat configuration format which is sensitive to parameter data type. So the following should now be working:

    import dallinger as dlgr
    exp = dlgr.experiments.Bartlett1932()
    exp.sandbox({"dyno_type": u"hobby"})

**Comment by suchow** [comment]
Closing this because when @alecpm's sample code is run on `development`, it gets passed this issue. I note, however, that this does not actually succeed in launching the experiment on the sandbox, breaking for other reasons that I'm also seeing with `dallinger sandbox`.
