### ISSUE TITLE
Better error checking for experiment id

### ISSUE THREAD

**Issue by jhamrick** [Dallinger/Dallinger#406]
Feature request: check whether people have put in a valid experiment id, and give a more helpful error message if not.

## Expected Behavior

If the user uses the prefix `dlgr-`, then the command should say somehting along the lines of "We detected you used the `dlgr-` prefix for the experiment id, please use the full experiment id instead."

If they give an otherwise invalid id, catch the error and print a nicer error message rather than showing the long traceback. Something like "Invalid experiment id."

## Current Behavior

If you put in an invalid experiment id, for example to the `logs` command, you don't get a super useful error message:

```
$ dallinger logs --app dlgr-4f78efa4
 ▸    Ambiguous identifier; multiple matching add-ons found: papertrail-animated-25171, papertrail-polished-61694,
 ▸    papertrail-infinite-77837, papertrail-concave-99350, papertrail-spherical-72030, papertrail-angular-46831,
 ▸    papertrail-sinuous-54204, papertrail-dimensional-39607, papertrail-trapezoidal-75902, papertrail-shaped-75393,
 ▸    papertrail-silhouetted-51900, papertrail-clean-53096, papertrail-fluffy-83202, papertrail-spherical-79413,
 ▸    papertrail-rigid-83927, papertrail-rectangular-98600, papertrail-animate-17760, papertrail-transparent-78392,
 ▸    papertrail-animated-82927.
Traceback (most recent call last):
  File "/Users/jhamrick/miniconda3/envs/dallinger/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/Users/jhamrick/miniconda3/envs/dallinger/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jhamrick/miniconda3/envs/dallinger/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/jhamrick/miniconda3/envs/dallinger/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jhamrick/miniconda3/envs/dallinger/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jhamrick/miniconda3/envs/dallinger/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/jhamrick/project/research/dallinger/dallinger/command_line.py", line 886, in logs
    shell=True)
  File "/Users/jhamrick/miniconda3/envs/dallinger/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'heroku addons:open papertrail --app dlgr-dlgr-4f7' returned non-zero exit status 1
```

In particular, this is the id that dallinger itself printed out, so I didn't understand at first why it was incorrect.

## Your Environment

* Dallinger version used: master

**Comment by suchow** [comment]
Fixed via #566.
