### ISSUE TITLE
Can't debug: No option 'clock_on' in section: 'Server Parameters' 

### ISSUE THREAD

**Issue by Yuan-Meng** [Dallinger/Dallinger#481]
## Expected Behavior

Hi! I followed every step of the instructions until [this far](http://dallinger.readthedocs.io/en/v2.7.0/demoing_dallinger.html). After entering "dallinger debug", I should be able to see a psiTurk prompt:
`Now serving on http://0.0.0.0:5000`
`[psiTurk server:on mode:sdbx #HITs:4]$`

## Current Behavior

But instead, I got the following error message:
`❯❯ Verifying that directory is compatible with Dallinger...

❯❯ Experiment id is 1bec4ccc-d7e8-4073-88d8-7f9d4810455c
/var/folders/xj/q71rvy1d17574pg8z4fv572m0000gn/T/tmppHrIEf/1bec4ccc-d7e8-4073-88d8-7f9d4810455c
Traceback (most recent call last):
  File "/Users/apple/Library/Enthought/Canopy_64bit/User/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger==2.7.0', 'console_scripts', 'dallinger')()
  File "/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/apple/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/dallinger/command_line.py", line 244, in debug
    (id, tmp) = setup_experiment(debug=True, verbose=verbose)
  File "/Users/apple/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/dallinger/command_line.py", line 190, in setup_experiment
    clock_on = config.getboolean('Server Parameters', 'clock_on')
  File "/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/ConfigParser.py", line 368, in getboolean
    v = self.get(section, option)
  File "/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'clock_on' in section: 'Server Parameters'`

As a result, I can't run experiments on Dallinger and want to know how to fix this issue. Thanks!
## My Environment

* Dallinger version used: 2.7.0
* Python version: 2.7.11
* Operating System: MacOS Sierra

**Comment by suchow** [comment]
@Yuan-Meng Ah, I see there's a versioning issue in the documentation — the demo you downloaded from the docs isn't compatible with 2.7.0 because the link is wrong. Can you try this one instead and see if it helps?

http://dallinger.readthedocs.io/en/v2.7.0/_static/bartlett1932.zip

**Comment by Yuan-Meng** [comment]
@suchow Thank you, Jordan! With the new file, I was able to launch psiTurk shell, but a new problems occurred:

"curl: (7) Failed to connect to 0.0.0.0 port a: Connection refused"

and as a result,

"Your psiTurk server is currently not running but you are trying to create an Ad/HIT.  This can cause problems for worker trying to access your hit.  Please start the server by first typing 'server on' then try this command again."

Then, I changed the port in .dallingerconfig from 5000 to 22362, which matches psiTurk's port, but I still received the second part of the error message. What do you think caused that? Thanks!

**Comment by suchow** [comment]
@Yuan-Meng Because the original problem you found is now fixed, I'm going to close this particular issue, but feel free to open a new issue for the next problem you encountered.

**Comment by Yuan-Meng** [comment]
@suchow Sure! Thanks!!
