### ISSUE TITLE
Allow qualify to run in any directory

### ISSUE THREAD

**Issue by thomasmorgan** [Dallinger/Dallinger#505]
The qualify CLI command could, in theory, run in any directory, right? Currently you have to be within a valid experiment directory for it to execute. This feels odd.

**Comment by suchow** [comment]
What version are you on? I can't replicate this on `master`.

**Comment by thomasmorgan** [comment]
I am on master too, interesting. Will investigate further next time I am qualifying people (later today probably)

**Comment by suchow** [comment]
One hint here is that I ran `dallinger qualify` but did not give it any parameters, leading it to break on line 542 of `command_line.py`, which means it must be one of these calls:

```
    if mturk.set_qualification_score(qualification, worker, value):
        click.echo('OK')

    # print out the current set of workers with the qualification
    results = list(mturk.get_workers_with_qualification(qualification))
```

**Comment by thomasmorgan** [comment]
Here's the error I get when running qualify out of an experiment directory. Looks like an error from AWS:

```
(dallinger)Thomass-MacBook-Pro-2:~ Tom$ dlgr qualify --qualification 3QA4K48P72MYD9MN0N5GEG1CTWUTMT --value 26 --worker <REDACTED>
Assigning qualification 3QA4K48P72MYD9MN0N5GEG1CTWUTMT with value 26 to worker <REDACTED>
Traceback (most recent call last):
  File "/Users/Tom/.virtualenvs/dallinger/bin/dallinger", line 9, in <module>
    load_entry_point('dallinger==2.7.0', 'console_scripts', 'dallinger')()
  File "/Users/Tom/.virtualenvs/dallinger/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Tom/.virtualenvs/dallinger/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/Tom/.virtualenvs/dallinger/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Tom/.virtualenvs/dallinger/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Tom/.virtualenvs/dallinger/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/Tom/Documents/Wallace/Dallinger/dallinger/command_line.py", line 542, in qualify
    if mturk.set_qualification_score(qualification, worker, value):
  File "/Users/Tom/Documents/Wallace/Dallinger/dallinger/mturk.py", line 164, in set_qualification_score
    w['id'] for w in self.get_workers_with_qualification(qualification_id)
  File "/Users/Tom/Documents/Wallace/Dallinger/dallinger/mturk.py", line 150, in get_workers_with_qualification
    page_number=page
  File "/Users/Tom/.virtualenvs/dallinger/lib/python2.7/site-packages/boto/mturk/connection.py", line 699, in get_qualifications_for_qualification_type
    [('Qualification', Qualification)])
  File "/Users/Tom/.virtualenvs/dallinger/lib/python2.7/site-packages/boto/mturk/connection.py", line 821, in _process_request
    return self._process_response(response, marker_elems)
  File "/Users/Tom/.virtualenvs/dallinger/lib/python2.7/site-packages/boto/mturk/connection.py", line 836, in _process_response
    raise MTurkRequestError(response.status, response.reason, body)
boto.mturk.connection.MTurkRequestError: MTurkRequestError: 200 OK
<?xml version="1.0"?>
<GetQualificationsForQualificationTypeResponse><OperationRequest><RequestId>da5e4875-9727-4d33-ae54-1e93a64c868c</RequestId></OperationRequest><GetQualificationsForQualificationTypeResult><Request><IsValid>False</IsValid><Errors><Error><Code>AWS.MechanicalTurk.QualificationTypeDoesNotExist</Code><Message>QualificationType 3QA4K48P72MYD9MN0N5GEG1CTWUTMT does not exist. (1489101763693 s)</Message><Data><Key>QualificationTypeId</Key><Value>3QA4K48P72MYD9MN0N5GEG1CTWUTMT</Value></Data><Data><Key>QualificationTypeId</Key><Value>3QA4K48P72MYD9MN0N5GEG1CTWUTMT</Value></Data></Error></Errors></Request></GetQualificationsForQualificationTypeResult></GetQualificationsForQualificationTypeResponse>
```

**Comment by thomasmorgan** [comment]
but it definitely works from within an experiment directory
