### ISSUE TITLE
little guarantee of the ability to download zip files larger than 800mb

### ISSUE THREAD

**Issue by jcpeterson** [Dallinger/Dallinger#588]
After my dataset swelled to around 850mb, I got the following error when trying to download and save using dallinger export:

```
Traceback (most recent call last):
  File "/usr/local/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger==2.7.2', 'console_scripts', 'dallinger')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dallinger/command_line.py", line 869, in export
    os.path.join("data", id)
  File "/usr/lib/python2.7/shutil.py", line 548, in make_archive
    filename = func(base_name, base_dir, **kwargs)
  File "/usr/lib/python2.7/shutil.py", line 456, in _make_zipfile
    zf.write(path, path)
  File "/usr/lib/python2.7/zipfile.py", line 1141, in write
    self._writecheck(zinfo)
  File "/usr/lib/python2.7/zipfile.py", line 1106, in _writecheck
    raise LargeZipFile("Filesize would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions
```

I fixed this myself by editing zipfile.py, which is not a good option. In particular, I set the default of
`zipfile.ZipFile(file, mode='r', compression=ZIP_STORED, allowZip64=False)`
to
`zipfile.ZipFile(file, mode='r', compression=ZIP_STORED, allowZip64=True)
`
It seems that this issue doesn't effect all platforms and python versions (I'm on 2.7.6). Passing allowZip64=True in dallinger isn't possible since it uses shutil to save the zip file, and shutil has no relevant argument for setting this option. The safer solution might require using and controlling zipfile directly and copying after if needed.

**Comment by vlall** [comment]
Fixed in #601.
