### ISSUE TITLE
Import errors in demo's experiment.py file swallowed by config.register_extra_parameters()

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#602]
## Expected Behavior
If a demo imports `some_package` and that package is not available, an ImportError should be raised.

## Current Behavior
Currently the problem is swallowed, only to manifest later when the experiment's custom config parameters have failed to load. For example:
```
Traceback (most recent call last):
  File "/Users/jesses/.virtualenvs/dallinger2/bin/dallinger", line 9, in <module>
    load_entry_point('dallinger==2.7.0', 'console_scripts', 'dallinger')()
  File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/Users/jesses/.virtualenvs/dallinger2/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/jesses/py_dev/Dallinger2/dallinger/__init__.py", line 3, in <module>
    from . import (
  File "/Users/jesses/py_dev/Dallinger2/dallinger/experiments/__init__.py", line 11, in <module>
    config.load()
  File "/Users/jesses/py_dev/Dallinger2/dallinger/config.py", line 216, in load
    self.load_from_file(localConfig)
  File "/Users/jesses/py_dev/Dallinger2/dallinger/config.py", line 176, in load_from_file
    self.extend(data, cast_types=True, strict=True)
  File "/Users/jesses/py_dev/Dallinger2/dallinger/config.py", line 95, in extend
    raise KeyError('{} is not a valid configuration key'.format(key))
KeyError: u'max_participants is not a valid configuration key'
```

The **actual** problem here was that the experiment includes the following import statement:
`from faker import Factory`
but `faker` is not installed.

## Your Environment

* Dallinger version used: `development` branch with `Griduniverse` demo

**Comment by jessesnyder** [comment]
Closing, post-merge.
