### ISSUE TITLE
"dallinger ec2 list instances" fails if an EC2 instance has no "Name" assigned

### ISSUE THREAD

**Issue by fmhoeger** [Dallinger/Dallinger#7103]
Error log:
```
✗ ddallinger ec2 list instances
2024-11-06 18:06:36,074 - dallinger.command_line.lib.ec2 - INFO - Getting instances...
2024-11-06 18:06:36,074 - dallinger.command_line.lib.ec2 - WARNING - Listing instances in all regions...
Retrieving instances in eu-central-1:  71%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                               | 12/17 [01:21<00:33,  6.77s/it]
Traceback (most recent call last):
  File "/home/frank/.virtualenvs/psynet-3.12/bin/dallinger", line 8, in <module>
    sys.exit(dallinger())
             ^^^^^^^^^^^
  File "/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/.virtualenvs/psynet-3.12/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/projects/Dallinger/dallinger/command_line/ec2.py", line 80, in list__instances
    list_instances(region, filtered_states=filtered_states, pem=pem)
  File "/home/frank/projects/Dallinger/dallinger/command_line/lib/ec2.py", line 121, in list_instances
    instance_df = get_all_instances(region_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/projects/Dallinger/dallinger/command_line/lib/ec2.py", line 111, in get_all_instances
    instance_dfs.append(get_instances(region["RegionName"]))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frank/projects/Dallinger/dallinger/command_line/lib/ec2.py", line 89, in get_instances
    "name": instance["Tags"][0]["Value"],
            ~~~~~~~~^^^^^^^^
KeyError: 'Tags'
```

**Comment by polvanrijn** [comment]
I already fixed this in my PR: https://github.com/Dallinger/Dallinger/pull/7016

**Comment by fmhoeger** [comment]
Closed as fixed in https://github.com/Dallinger/Dallinger/pull/7016
