### ISSUE TITLE
Make `dallinger destroy` understand full UUIDs

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#730]
```
(dallinger) ➜  bartlett1932 git:(stories/73-manual-recruitment) ✗ heroku destroy --app d9e63583-51be-4391-a162-d18fc37821cb
 ▸    Couldn't find that app.
Error: ENOENT: no such file or directory, open '/Users/jordansuchow/.cache/heroku/error.log'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1314:33)
    at Object.fs.appendFileSync (fs.js:1360:6)
    at log (/Users/jordansuchow/.local/share/heroku/client/node_modules/heroku-apps/node_modules/heroku-cli-util/lib/errors.js:87:6)
    at handleErr (/Users/jordansuchow/.local/share/heroku/client/node_modules/heroku-apps/node_modules/heroku-cli-util/lib/errors.js:102:9)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by suchow** [comment]
(Oops, nvm.)
