### ISSUE TITLE
monitor error

### ISSUE THREAD

**Issue by lottybrand22** [Dallinger/Dallinger#747]
3 windows opened and nothing happened, Dallinger v3.4.1

```(dallinger) lottys-mbp:griduniverse LottyBrand$ dallinger monitor --app 6b406608-8932-4c99-2aa1-34cdd60bdf9a
Opening https://addons-sso.heroku.com/apps/ea935faa-e723-4c40-81f2-46a7eb586c1a/addons/9d92bcd2-e99b-4390-8197-67847e211208...
 ▸    pg:credentials has recently changed. Please use pg:credentials:url for the
 ▸    previous output.
Traceback (most recent call last):
  File "/Users/LottyBrand/.virtualenvs/dallinger/bin/dallinger", line 11, in <module>
    load_entry_point('dallinger', 'console_scripts', 'dallinger')()
  File "/Users/LottyBrand/.virtualenvs/dallinger/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/LottyBrand/.virtualenvs/dallinger/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/LottyBrand/.virtualenvs/dallinger/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/LottyBrand/.virtualenvs/dallinger/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/LottyBrand/.virtualenvs/dallinger/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/LottyBrand/Desktop/Postdoc/Dallinger/dallinger/command_line.py", line 907, in monitor
    subprocess.call(["open", heroku_app.db_uri])
  File "/Users/LottyBrand/Desktop/Postdoc/Dallinger/dallinger/heroku/tools.py", line 83, in db_uri
    output = self.get("DATABASE", subcommand="pg:credentials")
  File "/Users/LottyBrand/Desktop/Postdoc/Dallinger/dallinger/heroku/tools.py", line 120, in get
    return self._result(cmd)
  File "/Users/LottyBrand/Desktop/Postdoc/Dallinger/dallinger/heroku/tools.py", line 184, in _result
    return subprocess.check_output(cmd).decode(self.sys_encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 44: ordinal not in range(128)```

**Comment by suchow** [comment]
Closed by #748.
