### ISSUE TITLE
Runtime error when closing recruitment

### ISSUE THREAD

**Issue by suchow** [Dallinger/Dallinger#787]
```
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1: AttributeError: 'function' object has no attribute 'close_recruitment' 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1: Traceback (most recent call last): 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/python/lib/python2.7/site-packages/rq/worker.py", line 713, in perform_job 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     rv = job.perform() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/python/lib/python2.7/site-packages/rq/job.py", line 556, in perform 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     self._result = self._execute() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/python/lib/python2.7/site-packages/rq/job.py", line 562, in _execute 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     return self.func(*self.args, **self.kwargs) 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/src/dallinger/dallinger/db.py", line 85, in wrapper 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     return func(*args, **kwargs) 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/src/dallinger/dallinger/experiment_server/experiment_server.py", line 1414, in worker_function 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     runner() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/src/dallinger/dallinger/experiment_server/worker_events.py", line 100, in __call__ 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     self.experiment.recruit() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "dallinger_experiment.py", line 1052, in recruit 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     self.recruiter.close_recruitment() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1: AttributeError: 'function' object has no attribute 'close_recruitment' Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1: AttributeError: 'function' object has no attribute 'close_recruitment' 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1: Traceback (most recent call last): 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/python/lib/python2.7/site-packages/rq/worker.py", line 713, in perform_job 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     rv = job.perform() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/python/lib/python2.7/site-packages/rq/job.py", line 556, in perform 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     self._result = self._execute() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/python/lib/python2.7/site-packages/rq/job.py", line 562, in _execute 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     return self.func(*self.args, **self.kwargs) 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/src/dallinger/dallinger/db.py", line 85, in wrapper 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     return func(*args, **kwargs) 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/src/dallinger/dallinger/experiment_server/experiment_server.py", line 1414, in worker_function 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     runner() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "/app/.heroku/src/dallinger/dallinger/experiment_server/worker_events.py", line 100, in __call__ 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     self.experiment.recruit() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:   File "dallinger_experiment.py", line 1052, in recruit 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1:     self.recruiter.close_recruitment() 
Nov 03 09:06:43 dlgr-7f3f55c8 app/worker.1: AttributeError: 'function' object has no attribute 'close_recruitment' 
```

**Comment by vlall** [comment]
This is related to https://github.com/Dallinger/Griduniverse/blob/accbd78bfc055c39159cd608e87d2442d3382fc3/dlgr/griduniverse/experiment.py#L1052

`self.recruiter.close_recruitment()` is being referenced as an @property instead of a method `self.recruiter().close_recruitment()`. I saw a discussion on this here: https://github.com/Dallinger/Griduniverse/pull/135

**Comment by jessesnyder** [comment]
Yes, this is an incompatibility between the version of `dallinger` and the context running it. My guess would be a custom experiment compatible with dallinger's development branch, but run using master or a release.
