### ISSUE TITLE
Same participant error 

### ISSUE THREAD

**Issue by pkrafft** [Dallinger/Dallinger#827]
## Expected Behavior
"Same participant error" should only occur when one participant opens the page on multiple tabs or browsers

## Current Behavior
A single browser tab is being detected as same participant --- probably because line 175 of dallinger.js new Fingerprint2() is an asynchronous call (https://stackoverflow.com/questions/39768888/how-to-store-fingerprint2-result-in-a-var), but it is being treated synchronously in the code. I expect this leads to fingerprint_hash being undefined and then "undefined" being a key in the table that leads multiple distinct participants to be treated as the same participant.

## Steps to Reproduce (for bugs)
Deploy Bartlett demo

## Context
I am just guessing at the presence and cause of this error, but if it is as I suspect, the bug is critical. It prevented me from collecting any data using the developer version of dallinger, and has damaged our reputation on turkopticon.

## Your Environment
Using commit f3b26695d955631e4783f19db57ddfd7498eea83

**Comment by a-paxton** [comment]
I'm experiencing the same issue. Importantly, I *don't* see this error in `sandbox`—only in `deploy`. Here's a snippet from my Papertrail logs (once for every participant after the first):

```
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  2018-01-25 23:17:07,124 Response headers: [('server', 'MTurk'), ('content-type', 'text/xml'), ('transfer-encoding', 'chunked'), ('date', 'Thu, 25 Jan 2018 23:17:06 GMT')] 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  2018-01-25 23:17:07,334 Exception during scoped worker transaction, rolling back. 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  Traceback (most recent call last): 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/src/dallinger/dallinger/db.py", line 57, in sessions_scope 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      local_session.commit() 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 153, in do 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      return getattr(self.registry(), name)(*args, **kwargs) 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      self.transaction.commit() 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 471, in commit 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      t[1].commit() 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1643, in commit 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      self._do_commit() 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1674, in _do_commit 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      self.connection._commit_impl() 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 726, in _commit_impl 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      self._handle_dbapi_exception(e, None, None, None, None) 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      exc_info 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      reraise(type(exception), exception, tb=exc_tb, cause=cause) 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 724, in _commit_impl 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      self.engine.dialect.do_commit(self.connection) 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 460, in do_commit 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:      dbapi_connection.commit() 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  OperationalError: (psycopg2.extensions.TransactionRollbackError) could not serialize access due to read/write dependencies among transactions 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  DETAIL:  Reason code: Canceled on identification as a pivot, during commit attempt. 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  HINT:  The transaction might succeed if retried. 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:   (Background on this error at: http://sqlalche.me/e/e3q8) 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  2018-01-25 23:17:07,445 Session complete, db session closed 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  2018-01-25 23:17:07,491 Same browser fingerprint detected. 
Jan 25 15:17:07 dlgr-a783c66f app/web.2:  2018-01-25 23:17:07,511 Failure for request: {} 
```

**Comment by MatthewWilkes** [comment]
@a-paxton's issue is slightly different in cause, but it's effectively the same issue. The fingerprinting was added in PR #706 and `dallinger.js` was refactored into `dallinger2.js` in #716. As you can guess from the numbers, these were happening at the same time, in fact it appears that the fingerprinting work was started before the `dallinger2.js` work but didn't merge until after `dallinger2`, which means *no experiments using `dallinger2.js` generate a fingerprint*. In addition, having no fingerprint passed results in a `None` being stored as the fingerprint, making all users appear as duplicates.

My proposed fix is to disregard `None` fingerprints when checking for duplicates and to port the fingerprint work to dallinger2.
